packages:
  - apis/*
  - plugins/*
  - dbs/*
  - libs/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - better-sqlite3
  - esbuild
  - nx
  - prisma
  - prisma-zod-generator
  - unrs-resolver
