
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Status = {
  ACTIVE: 'ACTIVE',
  PASSIVE: 'PASSIVE'
} as const

export type Status = (typeof Status)[keyof typeof Status]


export const Scope = {
  APP: 'APP',
  Low: 'Low',
  High: 'High'
} as const

export type Scope = (typeof Scope)[keyof typeof Scope]
