
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccessTokenPermissions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AccessTokenPermissions
 * 
 */
export type AccessTokenPermissionsModel = runtime.Types.Result.DefaultSelection<Prisma.$AccessTokenPermissionsPayload>

export type AggregateAccessTokenPermissions = {
  _count: AccessTokenPermissionsCountAggregateOutputType | null
  _avg: AccessTokenPermissionsAvgAggregateOutputType | null
  _sum: AccessTokenPermissionsSumAggregateOutputType | null
  _min: AccessTokenPermissionsMinAggregateOutputType | null
  _max: AccessTokenPermissionsMaxAggregateOutputType | null
}

export type AccessTokenPermissionsAvgAggregateOutputType = {
  id: number | null
  accessTokenId: number | null
  permissionId: number | null
}

export type AccessTokenPermissionsSumAggregateOutputType = {
  id: number | null
  accessTokenId: number | null
  permissionId: number | null
}

export type AccessTokenPermissionsMinAggregateOutputType = {
  id: number | null
  uuid: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  accessTokenId: number | null
  permissionId: number | null
}

export type AccessTokenPermissionsMaxAggregateOutputType = {
  id: number | null
  uuid: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
  accessTokenId: number | null
  permissionId: number | null
}

export type AccessTokenPermissionsCountAggregateOutputType = {
  id: number
  uuid: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  accessTokenId: number
  permissionId: number
  _all: number
}


export type AccessTokenPermissionsAvgAggregateInputType = {
  id?: true
  accessTokenId?: true
  permissionId?: true
}

export type AccessTokenPermissionsSumAggregateInputType = {
  id?: true
  accessTokenId?: true
  permissionId?: true
}

export type AccessTokenPermissionsMinAggregateInputType = {
  id?: true
  uuid?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  accessTokenId?: true
  permissionId?: true
}

export type AccessTokenPermissionsMaxAggregateInputType = {
  id?: true
  uuid?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  accessTokenId?: true
  permissionId?: true
}

export type AccessTokenPermissionsCountAggregateInputType = {
  id?: true
  uuid?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  accessTokenId?: true
  permissionId?: true
  _all?: true
}

export type AccessTokenPermissionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccessTokenPermissions to aggregate.
   */
  where?: Prisma.AccessTokenPermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessTokenPermissions to fetch.
   */
  orderBy?: Prisma.AccessTokenPermissionsOrderByWithRelationInput | Prisma.AccessTokenPermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccessTokenPermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessTokenPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessTokenPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccessTokenPermissions
  **/
  _count?: true | AccessTokenPermissionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccessTokenPermissionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccessTokenPermissionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccessTokenPermissionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccessTokenPermissionsMaxAggregateInputType
}

export type GetAccessTokenPermissionsAggregateType<T extends AccessTokenPermissionsAggregateArgs> = {
      [P in keyof T & keyof AggregateAccessTokenPermissions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccessTokenPermissions[P]>
    : Prisma.GetScalarType<T[P], AggregateAccessTokenPermissions[P]>
}




export type AccessTokenPermissionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccessTokenPermissionsWhereInput
  orderBy?: Prisma.AccessTokenPermissionsOrderByWithAggregationInput | Prisma.AccessTokenPermissionsOrderByWithAggregationInput[]
  by: Prisma.AccessTokenPermissionsScalarFieldEnum[] | Prisma.AccessTokenPermissionsScalarFieldEnum
  having?: Prisma.AccessTokenPermissionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccessTokenPermissionsCountAggregateInputType | true
  _avg?: AccessTokenPermissionsAvgAggregateInputType
  _sum?: AccessTokenPermissionsSumAggregateInputType
  _min?: AccessTokenPermissionsMinAggregateInputType
  _max?: AccessTokenPermissionsMaxAggregateInputType
}

export type AccessTokenPermissionsGroupByOutputType = {
  id: number
  uuid: string
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  accessTokenId: number
  permissionId: number
  _count: AccessTokenPermissionsCountAggregateOutputType | null
  _avg: AccessTokenPermissionsAvgAggregateOutputType | null
  _sum: AccessTokenPermissionsSumAggregateOutputType | null
  _min: AccessTokenPermissionsMinAggregateOutputType | null
  _max: AccessTokenPermissionsMaxAggregateOutputType | null
}

type GetAccessTokenPermissionsGroupByPayload<T extends AccessTokenPermissionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccessTokenPermissionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccessTokenPermissionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccessTokenPermissionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccessTokenPermissionsGroupByOutputType[P]>
      }
    >
  >



export type AccessTokenPermissionsWhereInput = {
  AND?: Prisma.AccessTokenPermissionsWhereInput | Prisma.AccessTokenPermissionsWhereInput[]
  OR?: Prisma.AccessTokenPermissionsWhereInput[]
  NOT?: Prisma.AccessTokenPermissionsWhereInput | Prisma.AccessTokenPermissionsWhereInput[]
  id?: Prisma.IntFilter<"AccessTokenPermissions"> | number
  uuid?: Prisma.StringFilter<"AccessTokenPermissions"> | string
  createdAt?: Prisma.DateTimeFilter<"AccessTokenPermissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccessTokenPermissions"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"AccessTokenPermissions"> | Date | string | null
  accessTokenId?: Prisma.IntFilter<"AccessTokenPermissions"> | number
  permissionId?: Prisma.IntFilter<"AccessTokenPermissions"> | number
  accessToken?: Prisma.XOR<Prisma.AccessTokenScalarRelationFilter, Prisma.AccessTokenWhereInput>
  permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>
}

export type AccessTokenPermissionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  accessTokenId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  accessToken?: Prisma.AccessTokenOrderByWithRelationInput
  permission?: Prisma.PermissionOrderByWithRelationInput
}

export type AccessTokenPermissionsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  uuid?: string
  accessTokenId_permissionId?: Prisma.AccessTokenPermissionsAccessTokenIdPermissionIdCompoundUniqueInput
  AND?: Prisma.AccessTokenPermissionsWhereInput | Prisma.AccessTokenPermissionsWhereInput[]
  OR?: Prisma.AccessTokenPermissionsWhereInput[]
  NOT?: Prisma.AccessTokenPermissionsWhereInput | Prisma.AccessTokenPermissionsWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"AccessTokenPermissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccessTokenPermissions"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"AccessTokenPermissions"> | Date | string | null
  accessTokenId?: Prisma.IntFilter<"AccessTokenPermissions"> | number
  permissionId?: Prisma.IntFilter<"AccessTokenPermissions"> | number
  accessToken?: Prisma.XOR<Prisma.AccessTokenScalarRelationFilter, Prisma.AccessTokenWhereInput>
  permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>
}, "id" | "uuid" | "accessTokenId_permissionId">

export type AccessTokenPermissionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  accessTokenId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  _count?: Prisma.AccessTokenPermissionsCountOrderByAggregateInput
  _avg?: Prisma.AccessTokenPermissionsAvgOrderByAggregateInput
  _max?: Prisma.AccessTokenPermissionsMaxOrderByAggregateInput
  _min?: Prisma.AccessTokenPermissionsMinOrderByAggregateInput
  _sum?: Prisma.AccessTokenPermissionsSumOrderByAggregateInput
}

export type AccessTokenPermissionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccessTokenPermissionsScalarWhereWithAggregatesInput | Prisma.AccessTokenPermissionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccessTokenPermissionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccessTokenPermissionsScalarWhereWithAggregatesInput | Prisma.AccessTokenPermissionsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AccessTokenPermissions"> | number
  uuid?: Prisma.StringWithAggregatesFilter<"AccessTokenPermissions"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccessTokenPermissions"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AccessTokenPermissions"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"AccessTokenPermissions"> | Date | string | null
  accessTokenId?: Prisma.IntWithAggregatesFilter<"AccessTokenPermissions"> | number
  permissionId?: Prisma.IntWithAggregatesFilter<"AccessTokenPermissions"> | number
}

export type AccessTokenPermissionsCreateInput = {
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  accessToken: Prisma.AccessTokenCreateNestedOneWithoutAccessTokenPermissionsInput
  permission: Prisma.PermissionCreateNestedOneWithoutAccessTokenPermissionsInput
}

export type AccessTokenPermissionsUncheckedCreateInput = {
  id?: number
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  accessTokenId: number
  permissionId: number
}

export type AccessTokenPermissionsUpdateInput = {
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessToken?: Prisma.AccessTokenUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput
  permission?: Prisma.PermissionUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput
}

export type AccessTokenPermissionsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessTokenId?: Prisma.IntFieldUpdateOperationsInput | number
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AccessTokenPermissionsCreateManyInput = {
  id?: number
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  accessTokenId: number
  permissionId: number
}

export type AccessTokenPermissionsUpdateManyMutationInput = {
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type AccessTokenPermissionsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessTokenId?: Prisma.IntFieldUpdateOperationsInput | number
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AccessTokenPermissionsListRelationFilter = {
  every?: Prisma.AccessTokenPermissionsWhereInput
  some?: Prisma.AccessTokenPermissionsWhereInput
  none?: Prisma.AccessTokenPermissionsWhereInput
}

export type AccessTokenPermissionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccessTokenPermissionsAccessTokenIdPermissionIdCompoundUniqueInput = {
  accessTokenId: number
  permissionId: number
}

export type AccessTokenPermissionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  accessTokenId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type AccessTokenPermissionsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accessTokenId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type AccessTokenPermissionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  accessTokenId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type AccessTokenPermissionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  uuid?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  accessTokenId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type AccessTokenPermissionsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  accessTokenId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type AccessTokenPermissionsCreateNestedManyWithoutPermissionInput = {
  create?: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutPermissionInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput> | Prisma.AccessTokenPermissionsCreateWithoutPermissionInput[] | Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.AccessTokenPermissionsCreateOrConnectWithoutPermissionInput | Prisma.AccessTokenPermissionsCreateOrConnectWithoutPermissionInput[]
  createMany?: Prisma.AccessTokenPermissionsCreateManyPermissionInputEnvelope
  connect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
}

export type AccessTokenPermissionsUncheckedCreateNestedManyWithoutPermissionInput = {
  create?: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutPermissionInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput> | Prisma.AccessTokenPermissionsCreateWithoutPermissionInput[] | Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.AccessTokenPermissionsCreateOrConnectWithoutPermissionInput | Prisma.AccessTokenPermissionsCreateOrConnectWithoutPermissionInput[]
  createMany?: Prisma.AccessTokenPermissionsCreateManyPermissionInputEnvelope
  connect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
}

export type AccessTokenPermissionsUpdateManyWithoutPermissionNestedInput = {
  create?: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutPermissionInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput> | Prisma.AccessTokenPermissionsCreateWithoutPermissionInput[] | Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.AccessTokenPermissionsCreateOrConnectWithoutPermissionInput | Prisma.AccessTokenPermissionsCreateOrConnectWithoutPermissionInput[]
  upsert?: Prisma.AccessTokenPermissionsUpsertWithWhereUniqueWithoutPermissionInput | Prisma.AccessTokenPermissionsUpsertWithWhereUniqueWithoutPermissionInput[]
  createMany?: Prisma.AccessTokenPermissionsCreateManyPermissionInputEnvelope
  set?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  disconnect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  delete?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  connect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  update?: Prisma.AccessTokenPermissionsUpdateWithWhereUniqueWithoutPermissionInput | Prisma.AccessTokenPermissionsUpdateWithWhereUniqueWithoutPermissionInput[]
  updateMany?: Prisma.AccessTokenPermissionsUpdateManyWithWhereWithoutPermissionInput | Prisma.AccessTokenPermissionsUpdateManyWithWhereWithoutPermissionInput[]
  deleteMany?: Prisma.AccessTokenPermissionsScalarWhereInput | Prisma.AccessTokenPermissionsScalarWhereInput[]
}

export type AccessTokenPermissionsUncheckedUpdateManyWithoutPermissionNestedInput = {
  create?: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutPermissionInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput> | Prisma.AccessTokenPermissionsCreateWithoutPermissionInput[] | Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.AccessTokenPermissionsCreateOrConnectWithoutPermissionInput | Prisma.AccessTokenPermissionsCreateOrConnectWithoutPermissionInput[]
  upsert?: Prisma.AccessTokenPermissionsUpsertWithWhereUniqueWithoutPermissionInput | Prisma.AccessTokenPermissionsUpsertWithWhereUniqueWithoutPermissionInput[]
  createMany?: Prisma.AccessTokenPermissionsCreateManyPermissionInputEnvelope
  set?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  disconnect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  delete?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  connect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  update?: Prisma.AccessTokenPermissionsUpdateWithWhereUniqueWithoutPermissionInput | Prisma.AccessTokenPermissionsUpdateWithWhereUniqueWithoutPermissionInput[]
  updateMany?: Prisma.AccessTokenPermissionsUpdateManyWithWhereWithoutPermissionInput | Prisma.AccessTokenPermissionsUpdateManyWithWhereWithoutPermissionInput[]
  deleteMany?: Prisma.AccessTokenPermissionsScalarWhereInput | Prisma.AccessTokenPermissionsScalarWhereInput[]
}

export type AccessTokenPermissionsCreateNestedManyWithoutAccessTokenInput = {
  create?: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput> | Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput[] | Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput[]
  connectOrCreate?: Prisma.AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput | Prisma.AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput[]
  createMany?: Prisma.AccessTokenPermissionsCreateManyAccessTokenInputEnvelope
  connect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
}

export type AccessTokenPermissionsUncheckedCreateNestedManyWithoutAccessTokenInput = {
  create?: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput> | Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput[] | Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput[]
  connectOrCreate?: Prisma.AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput | Prisma.AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput[]
  createMany?: Prisma.AccessTokenPermissionsCreateManyAccessTokenInputEnvelope
  connect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
}

export type AccessTokenPermissionsUpdateManyWithoutAccessTokenNestedInput = {
  create?: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput> | Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput[] | Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput[]
  connectOrCreate?: Prisma.AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput | Prisma.AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput[]
  upsert?: Prisma.AccessTokenPermissionsUpsertWithWhereUniqueWithoutAccessTokenInput | Prisma.AccessTokenPermissionsUpsertWithWhereUniqueWithoutAccessTokenInput[]
  createMany?: Prisma.AccessTokenPermissionsCreateManyAccessTokenInputEnvelope
  set?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  disconnect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  delete?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  connect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  update?: Prisma.AccessTokenPermissionsUpdateWithWhereUniqueWithoutAccessTokenInput | Prisma.AccessTokenPermissionsUpdateWithWhereUniqueWithoutAccessTokenInput[]
  updateMany?: Prisma.AccessTokenPermissionsUpdateManyWithWhereWithoutAccessTokenInput | Prisma.AccessTokenPermissionsUpdateManyWithWhereWithoutAccessTokenInput[]
  deleteMany?: Prisma.AccessTokenPermissionsScalarWhereInput | Prisma.AccessTokenPermissionsScalarWhereInput[]
}

export type AccessTokenPermissionsUncheckedUpdateManyWithoutAccessTokenNestedInput = {
  create?: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput> | Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput[] | Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput[]
  connectOrCreate?: Prisma.AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput | Prisma.AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput[]
  upsert?: Prisma.AccessTokenPermissionsUpsertWithWhereUniqueWithoutAccessTokenInput | Prisma.AccessTokenPermissionsUpsertWithWhereUniqueWithoutAccessTokenInput[]
  createMany?: Prisma.AccessTokenPermissionsCreateManyAccessTokenInputEnvelope
  set?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  disconnect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  delete?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  connect?: Prisma.AccessTokenPermissionsWhereUniqueInput | Prisma.AccessTokenPermissionsWhereUniqueInput[]
  update?: Prisma.AccessTokenPermissionsUpdateWithWhereUniqueWithoutAccessTokenInput | Prisma.AccessTokenPermissionsUpdateWithWhereUniqueWithoutAccessTokenInput[]
  updateMany?: Prisma.AccessTokenPermissionsUpdateManyWithWhereWithoutAccessTokenInput | Prisma.AccessTokenPermissionsUpdateManyWithWhereWithoutAccessTokenInput[]
  deleteMany?: Prisma.AccessTokenPermissionsScalarWhereInput | Prisma.AccessTokenPermissionsScalarWhereInput[]
}

export type AccessTokenPermissionsCreateWithoutPermissionInput = {
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  accessToken: Prisma.AccessTokenCreateNestedOneWithoutAccessTokenPermissionsInput
}

export type AccessTokenPermissionsUncheckedCreateWithoutPermissionInput = {
  id?: number
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  accessTokenId: number
}

export type AccessTokenPermissionsCreateOrConnectWithoutPermissionInput = {
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
  create: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutPermissionInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput>
}

export type AccessTokenPermissionsCreateManyPermissionInputEnvelope = {
  data: Prisma.AccessTokenPermissionsCreateManyPermissionInput | Prisma.AccessTokenPermissionsCreateManyPermissionInput[]
  skipDuplicates?: boolean
}

export type AccessTokenPermissionsUpsertWithWhereUniqueWithoutPermissionInput = {
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
  update: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateWithoutPermissionInput, Prisma.AccessTokenPermissionsUncheckedUpdateWithoutPermissionInput>
  create: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutPermissionInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutPermissionInput>
}

export type AccessTokenPermissionsUpdateWithWhereUniqueWithoutPermissionInput = {
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
  data: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateWithoutPermissionInput, Prisma.AccessTokenPermissionsUncheckedUpdateWithoutPermissionInput>
}

export type AccessTokenPermissionsUpdateManyWithWhereWithoutPermissionInput = {
  where: Prisma.AccessTokenPermissionsScalarWhereInput
  data: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateManyMutationInput, Prisma.AccessTokenPermissionsUncheckedUpdateManyWithoutPermissionInput>
}

export type AccessTokenPermissionsScalarWhereInput = {
  AND?: Prisma.AccessTokenPermissionsScalarWhereInput | Prisma.AccessTokenPermissionsScalarWhereInput[]
  OR?: Prisma.AccessTokenPermissionsScalarWhereInput[]
  NOT?: Prisma.AccessTokenPermissionsScalarWhereInput | Prisma.AccessTokenPermissionsScalarWhereInput[]
  id?: Prisma.IntFilter<"AccessTokenPermissions"> | number
  uuid?: Prisma.StringFilter<"AccessTokenPermissions"> | string
  createdAt?: Prisma.DateTimeFilter<"AccessTokenPermissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccessTokenPermissions"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"AccessTokenPermissions"> | Date | string | null
  accessTokenId?: Prisma.IntFilter<"AccessTokenPermissions"> | number
  permissionId?: Prisma.IntFilter<"AccessTokenPermissions"> | number
}

export type AccessTokenPermissionsCreateWithoutAccessTokenInput = {
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  permission: Prisma.PermissionCreateNestedOneWithoutAccessTokenPermissionsInput
}

export type AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput = {
  id?: number
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  permissionId: number
}

export type AccessTokenPermissionsCreateOrConnectWithoutAccessTokenInput = {
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
  create: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput>
}

export type AccessTokenPermissionsCreateManyAccessTokenInputEnvelope = {
  data: Prisma.AccessTokenPermissionsCreateManyAccessTokenInput | Prisma.AccessTokenPermissionsCreateManyAccessTokenInput[]
  skipDuplicates?: boolean
}

export type AccessTokenPermissionsUpsertWithWhereUniqueWithoutAccessTokenInput = {
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
  update: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateWithoutAccessTokenInput, Prisma.AccessTokenPermissionsUncheckedUpdateWithoutAccessTokenInput>
  create: Prisma.XOR<Prisma.AccessTokenPermissionsCreateWithoutAccessTokenInput, Prisma.AccessTokenPermissionsUncheckedCreateWithoutAccessTokenInput>
}

export type AccessTokenPermissionsUpdateWithWhereUniqueWithoutAccessTokenInput = {
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
  data: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateWithoutAccessTokenInput, Prisma.AccessTokenPermissionsUncheckedUpdateWithoutAccessTokenInput>
}

export type AccessTokenPermissionsUpdateManyWithWhereWithoutAccessTokenInput = {
  where: Prisma.AccessTokenPermissionsScalarWhereInput
  data: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateManyMutationInput, Prisma.AccessTokenPermissionsUncheckedUpdateManyWithoutAccessTokenInput>
}

export type AccessTokenPermissionsCreateManyPermissionInput = {
  id?: number
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  accessTokenId: number
}

export type AccessTokenPermissionsUpdateWithoutPermissionInput = {
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessToken?: Prisma.AccessTokenUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput
}

export type AccessTokenPermissionsUncheckedUpdateWithoutPermissionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessTokenId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AccessTokenPermissionsUncheckedUpdateManyWithoutPermissionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  accessTokenId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AccessTokenPermissionsCreateManyAccessTokenInput = {
  id?: number
  uuid?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  permissionId: number
}

export type AccessTokenPermissionsUpdateWithoutAccessTokenInput = {
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  permission?: Prisma.PermissionUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput
}

export type AccessTokenPermissionsUncheckedUpdateWithoutAccessTokenInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AccessTokenPermissionsUncheckedUpdateManyWithoutAccessTokenInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  uuid?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type AccessTokenPermissionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uuid?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  accessTokenId?: boolean
  permissionId?: boolean
  accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accessTokenPermissions"]>

export type AccessTokenPermissionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uuid?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  accessTokenId?: boolean
  permissionId?: boolean
  accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accessTokenPermissions"]>

export type AccessTokenPermissionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  uuid?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  accessTokenId?: boolean
  permissionId?: boolean
  accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accessTokenPermissions"]>

export type AccessTokenPermissionsSelectScalar = {
  id?: boolean
  uuid?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  accessTokenId?: boolean
  permissionId?: boolean
}

export type AccessTokenPermissionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "uuid" | "createdAt" | "updatedAt" | "deletedAt" | "accessTokenId" | "permissionId", ExtArgs["result"]["accessTokenPermissions"]>
export type AccessTokenPermissionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}
export type AccessTokenPermissionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}
export type AccessTokenPermissionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accessToken?: boolean | Prisma.AccessTokenDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}

export type $AccessTokenPermissionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccessTokenPermissions"
  objects: {
    accessToken: Prisma.$AccessTokenPayload<ExtArgs>
    permission: Prisma.$PermissionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    uuid: string
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
    accessTokenId: number
    permissionId: number
  }, ExtArgs["result"]["accessTokenPermissions"]>
  composites: {}
}

export type AccessTokenPermissionsGetPayload<S extends boolean | null | undefined | AccessTokenPermissionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload, S>

export type AccessTokenPermissionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccessTokenPermissionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccessTokenPermissionsCountAggregateInputType | true
  }

export interface AccessTokenPermissionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccessTokenPermissions'], meta: { name: 'AccessTokenPermissions' } }
  /**
   * Find zero or one AccessTokenPermissions that matches the filter.
   * @param {AccessTokenPermissionsFindUniqueArgs} args - Arguments to find a AccessTokenPermissions
   * @example
   * // Get one AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccessTokenPermissionsFindUniqueArgs>(args: Prisma.SelectSubset<T, AccessTokenPermissionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccessTokenPermissionsClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccessTokenPermissions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccessTokenPermissionsFindUniqueOrThrowArgs} args - Arguments to find a AccessTokenPermissions
   * @example
   * // Get one AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccessTokenPermissionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccessTokenPermissionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccessTokenPermissionsClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccessTokenPermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessTokenPermissionsFindFirstArgs} args - Arguments to find a AccessTokenPermissions
   * @example
   * // Get one AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccessTokenPermissionsFindFirstArgs>(args?: Prisma.SelectSubset<T, AccessTokenPermissionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccessTokenPermissionsClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccessTokenPermissions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessTokenPermissionsFindFirstOrThrowArgs} args - Arguments to find a AccessTokenPermissions
   * @example
   * // Get one AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccessTokenPermissionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccessTokenPermissionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccessTokenPermissionsClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccessTokenPermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessTokenPermissionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.findMany()
   * 
   * // Get first 10 AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accessTokenPermissionsWithIdOnly = await prisma.accessTokenPermissions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccessTokenPermissionsFindManyArgs>(args?: Prisma.SelectSubset<T, AccessTokenPermissionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccessTokenPermissions.
   * @param {AccessTokenPermissionsCreateArgs} args - Arguments to create a AccessTokenPermissions.
   * @example
   * // Create one AccessTokenPermissions
   * const AccessTokenPermissions = await prisma.accessTokenPermissions.create({
   *   data: {
   *     // ... data to create a AccessTokenPermissions
   *   }
   * })
   * 
   */
  create<T extends AccessTokenPermissionsCreateArgs>(args: Prisma.SelectSubset<T, AccessTokenPermissionsCreateArgs<ExtArgs>>): Prisma.Prisma__AccessTokenPermissionsClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccessTokenPermissions.
   * @param {AccessTokenPermissionsCreateManyArgs} args - Arguments to create many AccessTokenPermissions.
   * @example
   * // Create many AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccessTokenPermissionsCreateManyArgs>(args?: Prisma.SelectSubset<T, AccessTokenPermissionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccessTokenPermissions and returns the data saved in the database.
   * @param {AccessTokenPermissionsCreateManyAndReturnArgs} args - Arguments to create many AccessTokenPermissions.
   * @example
   * // Create many AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccessTokenPermissions and only return the `id`
   * const accessTokenPermissionsWithIdOnly = await prisma.accessTokenPermissions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccessTokenPermissionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccessTokenPermissionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccessTokenPermissions.
   * @param {AccessTokenPermissionsDeleteArgs} args - Arguments to delete one AccessTokenPermissions.
   * @example
   * // Delete one AccessTokenPermissions
   * const AccessTokenPermissions = await prisma.accessTokenPermissions.delete({
   *   where: {
   *     // ... filter to delete one AccessTokenPermissions
   *   }
   * })
   * 
   */
  delete<T extends AccessTokenPermissionsDeleteArgs>(args: Prisma.SelectSubset<T, AccessTokenPermissionsDeleteArgs<ExtArgs>>): Prisma.Prisma__AccessTokenPermissionsClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccessTokenPermissions.
   * @param {AccessTokenPermissionsUpdateArgs} args - Arguments to update one AccessTokenPermissions.
   * @example
   * // Update one AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccessTokenPermissionsUpdateArgs>(args: Prisma.SelectSubset<T, AccessTokenPermissionsUpdateArgs<ExtArgs>>): Prisma.Prisma__AccessTokenPermissionsClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccessTokenPermissions.
   * @param {AccessTokenPermissionsDeleteManyArgs} args - Arguments to filter AccessTokenPermissions to delete.
   * @example
   * // Delete a few AccessTokenPermissions
   * const { count } = await prisma.accessTokenPermissions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccessTokenPermissionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccessTokenPermissionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccessTokenPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessTokenPermissionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccessTokenPermissionsUpdateManyArgs>(args: Prisma.SelectSubset<T, AccessTokenPermissionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccessTokenPermissions and returns the data updated in the database.
   * @param {AccessTokenPermissionsUpdateManyAndReturnArgs} args - Arguments to update many AccessTokenPermissions.
   * @example
   * // Update many AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccessTokenPermissions and only return the `id`
   * const accessTokenPermissionsWithIdOnly = await prisma.accessTokenPermissions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccessTokenPermissionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccessTokenPermissionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccessTokenPermissions.
   * @param {AccessTokenPermissionsUpsertArgs} args - Arguments to update or create a AccessTokenPermissions.
   * @example
   * // Update or create a AccessTokenPermissions
   * const accessTokenPermissions = await prisma.accessTokenPermissions.upsert({
   *   create: {
   *     // ... data to create a AccessTokenPermissions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccessTokenPermissions we want to update
   *   }
   * })
   */
  upsert<T extends AccessTokenPermissionsUpsertArgs>(args: Prisma.SelectSubset<T, AccessTokenPermissionsUpsertArgs<ExtArgs>>): Prisma.Prisma__AccessTokenPermissionsClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPermissionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccessTokenPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessTokenPermissionsCountArgs} args - Arguments to filter AccessTokenPermissions to count.
   * @example
   * // Count the number of AccessTokenPermissions
   * const count = await prisma.accessTokenPermissions.count({
   *   where: {
   *     // ... the filter for the AccessTokenPermissions we want to count
   *   }
   * })
  **/
  count<T extends AccessTokenPermissionsCountArgs>(
    args?: Prisma.Subset<T, AccessTokenPermissionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccessTokenPermissionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccessTokenPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessTokenPermissionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccessTokenPermissionsAggregateArgs>(args: Prisma.Subset<T, AccessTokenPermissionsAggregateArgs>): Prisma.PrismaPromise<GetAccessTokenPermissionsAggregateType<T>>

  /**
   * Group by AccessTokenPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessTokenPermissionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccessTokenPermissionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccessTokenPermissionsGroupByArgs['orderBy'] }
      : { orderBy?: AccessTokenPermissionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccessTokenPermissionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccessTokenPermissionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccessTokenPermissions model
 */
readonly fields: AccessTokenPermissionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccessTokenPermissions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccessTokenPermissionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  accessToken<T extends Prisma.AccessTokenDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccessTokenDefaultArgs<ExtArgs>>): Prisma.Prisma__AccessTokenClient<runtime.Types.Result.GetResult<Prisma.$AccessTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  permission<T extends Prisma.PermissionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PermissionDefaultArgs<ExtArgs>>): Prisma.Prisma__PermissionClient<runtime.Types.Result.GetResult<Prisma.$PermissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccessTokenPermissions model
 */
export interface AccessTokenPermissionsFieldRefs {
  readonly id: Prisma.FieldRef<"AccessTokenPermissions", 'Int'>
  readonly uuid: Prisma.FieldRef<"AccessTokenPermissions", 'String'>
  readonly createdAt: Prisma.FieldRef<"AccessTokenPermissions", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AccessTokenPermissions", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"AccessTokenPermissions", 'DateTime'>
  readonly accessTokenId: Prisma.FieldRef<"AccessTokenPermissions", 'Int'>
  readonly permissionId: Prisma.FieldRef<"AccessTokenPermissions", 'Int'>
}
    

// Custom InputTypes
/**
 * AccessTokenPermissions findUnique
 */
export type AccessTokenPermissionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which AccessTokenPermissions to fetch.
   */
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
}

/**
 * AccessTokenPermissions findUniqueOrThrow
 */
export type AccessTokenPermissionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which AccessTokenPermissions to fetch.
   */
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
}

/**
 * AccessTokenPermissions findFirst
 */
export type AccessTokenPermissionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which AccessTokenPermissions to fetch.
   */
  where?: Prisma.AccessTokenPermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessTokenPermissions to fetch.
   */
  orderBy?: Prisma.AccessTokenPermissionsOrderByWithRelationInput | Prisma.AccessTokenPermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccessTokenPermissions.
   */
  cursor?: Prisma.AccessTokenPermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessTokenPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessTokenPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccessTokenPermissions.
   */
  distinct?: Prisma.AccessTokenPermissionsScalarFieldEnum | Prisma.AccessTokenPermissionsScalarFieldEnum[]
}

/**
 * AccessTokenPermissions findFirstOrThrow
 */
export type AccessTokenPermissionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which AccessTokenPermissions to fetch.
   */
  where?: Prisma.AccessTokenPermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessTokenPermissions to fetch.
   */
  orderBy?: Prisma.AccessTokenPermissionsOrderByWithRelationInput | Prisma.AccessTokenPermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccessTokenPermissions.
   */
  cursor?: Prisma.AccessTokenPermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessTokenPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessTokenPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccessTokenPermissions.
   */
  distinct?: Prisma.AccessTokenPermissionsScalarFieldEnum | Prisma.AccessTokenPermissionsScalarFieldEnum[]
}

/**
 * AccessTokenPermissions findMany
 */
export type AccessTokenPermissionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * Filter, which AccessTokenPermissions to fetch.
   */
  where?: Prisma.AccessTokenPermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessTokenPermissions to fetch.
   */
  orderBy?: Prisma.AccessTokenPermissionsOrderByWithRelationInput | Prisma.AccessTokenPermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccessTokenPermissions.
   */
  cursor?: Prisma.AccessTokenPermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessTokenPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessTokenPermissions.
   */
  skip?: number
  distinct?: Prisma.AccessTokenPermissionsScalarFieldEnum | Prisma.AccessTokenPermissionsScalarFieldEnum[]
}

/**
 * AccessTokenPermissions create
 */
export type AccessTokenPermissionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * The data needed to create a AccessTokenPermissions.
   */
  data: Prisma.XOR<Prisma.AccessTokenPermissionsCreateInput, Prisma.AccessTokenPermissionsUncheckedCreateInput>
}

/**
 * AccessTokenPermissions createMany
 */
export type AccessTokenPermissionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccessTokenPermissions.
   */
  data: Prisma.AccessTokenPermissionsCreateManyInput | Prisma.AccessTokenPermissionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccessTokenPermissions createManyAndReturn
 */
export type AccessTokenPermissionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * The data used to create many AccessTokenPermissions.
   */
  data: Prisma.AccessTokenPermissionsCreateManyInput | Prisma.AccessTokenPermissionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AccessTokenPermissions update
 */
export type AccessTokenPermissionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * The data needed to update a AccessTokenPermissions.
   */
  data: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateInput, Prisma.AccessTokenPermissionsUncheckedUpdateInput>
  /**
   * Choose, which AccessTokenPermissions to update.
   */
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
}

/**
 * AccessTokenPermissions updateMany
 */
export type AccessTokenPermissionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccessTokenPermissions.
   */
  data: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateManyMutationInput, Prisma.AccessTokenPermissionsUncheckedUpdateManyInput>
  /**
   * Filter which AccessTokenPermissions to update
   */
  where?: Prisma.AccessTokenPermissionsWhereInput
  /**
   * Limit how many AccessTokenPermissions to update.
   */
  limit?: number
}

/**
 * AccessTokenPermissions updateManyAndReturn
 */
export type AccessTokenPermissionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * The data used to update AccessTokenPermissions.
   */
  data: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateManyMutationInput, Prisma.AccessTokenPermissionsUncheckedUpdateManyInput>
  /**
   * Filter which AccessTokenPermissions to update
   */
  where?: Prisma.AccessTokenPermissionsWhereInput
  /**
   * Limit how many AccessTokenPermissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AccessTokenPermissions upsert
 */
export type AccessTokenPermissionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * The filter to search for the AccessTokenPermissions to update in case it exists.
   */
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
  /**
   * In case the AccessTokenPermissions found by the `where` argument doesn't exist, create a new AccessTokenPermissions with this data.
   */
  create: Prisma.XOR<Prisma.AccessTokenPermissionsCreateInput, Prisma.AccessTokenPermissionsUncheckedCreateInput>
  /**
   * In case the AccessTokenPermissions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccessTokenPermissionsUpdateInput, Prisma.AccessTokenPermissionsUncheckedUpdateInput>
}

/**
 * AccessTokenPermissions delete
 */
export type AccessTokenPermissionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
  /**
   * Filter which AccessTokenPermissions to delete.
   */
  where: Prisma.AccessTokenPermissionsWhereUniqueInput
}

/**
 * AccessTokenPermissions deleteMany
 */
export type AccessTokenPermissionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccessTokenPermissions to delete
   */
  where?: Prisma.AccessTokenPermissionsWhereInput
  /**
   * Limit how many AccessTokenPermissions to delete.
   */
  limit?: number
}

/**
 * AccessTokenPermissions without action
 */
export type AccessTokenPermissionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessTokenPermissions
   */
  select?: Prisma.AccessTokenPermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessTokenPermissions
   */
  omit?: Prisma.AccessTokenPermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessTokenPermissionsInclude<ExtArgs> | null
}
