
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RolePermissions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model RolePermissions
 * 
 */
export type RolePermissionsModel = runtime.Types.Result.DefaultSelection<Prisma.$RolePermissionsPayload>

export type AggregateRolePermissions = {
  _count: RolePermissionsCountAggregateOutputType | null
  _avg: RolePermissionsAvgAggregateOutputType | null
  _sum: RolePermissionsSumAggregateOutputType | null
  _min: RolePermissionsMinAggregateOutputType | null
  _max: RolePermissionsMaxAggregateOutputType | null
}

export type RolePermissionsAvgAggregateOutputType = {
  id: number | null
  appId: number | null
  roleId: number | null
  resourceId: number | null
  permissionId: number | null
}

export type RolePermissionsSumAggregateOutputType = {
  id: number | null
  appId: number | null
  roleId: number | null
  resourceId: number | null
  permissionId: number | null
}

export type RolePermissionsMinAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  appName: string | null
  appId: number | null
  roleName: string | null
  roleId: number | null
  resourceName: string | null
  resourceId: number | null
  operationName: string | null
  permissionId: number | null
}

export type RolePermissionsMaxAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  appName: string | null
  appId: number | null
  roleName: string | null
  roleId: number | null
  resourceName: string | null
  resourceId: number | null
  operationName: string | null
  permissionId: number | null
}

export type RolePermissionsCountAggregateOutputType = {
  id: number
  createdAt: number
  appName: number
  appId: number
  roleName: number
  roleId: number
  resourceName: number
  resourceId: number
  operationName: number
  permissionId: number
  _all: number
}


export type RolePermissionsAvgAggregateInputType = {
  id?: true
  appId?: true
  roleId?: true
  resourceId?: true
  permissionId?: true
}

export type RolePermissionsSumAggregateInputType = {
  id?: true
  appId?: true
  roleId?: true
  resourceId?: true
  permissionId?: true
}

export type RolePermissionsMinAggregateInputType = {
  id?: true
  createdAt?: true
  appName?: true
  appId?: true
  roleName?: true
  roleId?: true
  resourceName?: true
  resourceId?: true
  operationName?: true
  permissionId?: true
}

export type RolePermissionsMaxAggregateInputType = {
  id?: true
  createdAt?: true
  appName?: true
  appId?: true
  roleName?: true
  roleId?: true
  resourceName?: true
  resourceId?: true
  operationName?: true
  permissionId?: true
}

export type RolePermissionsCountAggregateInputType = {
  id?: true
  createdAt?: true
  appName?: true
  appId?: true
  roleName?: true
  roleId?: true
  resourceName?: true
  resourceId?: true
  operationName?: true
  permissionId?: true
  _all?: true
}

export type RolePermissionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RolePermissions to aggregate.
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RolePermissions to fetch.
   */
  orderBy?: Prisma.RolePermissionsOrderByWithRelationInput | Prisma.RolePermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RolePermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RolePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RolePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RolePermissions
  **/
  _count?: true | RolePermissionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RolePermissionsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RolePermissionsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RolePermissionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RolePermissionsMaxAggregateInputType
}

export type GetRolePermissionsAggregateType<T extends RolePermissionsAggregateArgs> = {
      [P in keyof T & keyof AggregateRolePermissions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRolePermissions[P]>
    : Prisma.GetScalarType<T[P], AggregateRolePermissions[P]>
}




export type RolePermissionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RolePermissionsWhereInput
  orderBy?: Prisma.RolePermissionsOrderByWithAggregationInput | Prisma.RolePermissionsOrderByWithAggregationInput[]
  by: Prisma.RolePermissionsScalarFieldEnum[] | Prisma.RolePermissionsScalarFieldEnum
  having?: Prisma.RolePermissionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RolePermissionsCountAggregateInputType | true
  _avg?: RolePermissionsAvgAggregateInputType
  _sum?: RolePermissionsSumAggregateInputType
  _min?: RolePermissionsMinAggregateInputType
  _max?: RolePermissionsMaxAggregateInputType
}

export type RolePermissionsGroupByOutputType = {
  id: number
  createdAt: Date
  appName: string
  appId: number
  roleName: string
  roleId: number
  resourceName: string
  resourceId: number
  operationName: string
  permissionId: number
  _count: RolePermissionsCountAggregateOutputType | null
  _avg: RolePermissionsAvgAggregateOutputType | null
  _sum: RolePermissionsSumAggregateOutputType | null
  _min: RolePermissionsMinAggregateOutputType | null
  _max: RolePermissionsMaxAggregateOutputType | null
}

type GetRolePermissionsGroupByPayload<T extends RolePermissionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RolePermissionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RolePermissionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RolePermissionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RolePermissionsGroupByOutputType[P]>
      }
    >
  >



export type RolePermissionsWhereInput = {
  AND?: Prisma.RolePermissionsWhereInput | Prisma.RolePermissionsWhereInput[]
  OR?: Prisma.RolePermissionsWhereInput[]
  NOT?: Prisma.RolePermissionsWhereInput | Prisma.RolePermissionsWhereInput[]
  id?: Prisma.IntFilter<"RolePermissions"> | number
  createdAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
  appName?: Prisma.StringFilter<"RolePermissions"> | string
  appId?: Prisma.IntFilter<"RolePermissions"> | number
  roleName?: Prisma.StringFilter<"RolePermissions"> | string
  roleId?: Prisma.IntFilter<"RolePermissions"> | number
  resourceName?: Prisma.StringFilter<"RolePermissions"> | string
  resourceId?: Prisma.IntFilter<"RolePermissions"> | number
  operationName?: Prisma.StringFilter<"RolePermissions"> | string
  permissionId?: Prisma.IntFilter<"RolePermissions"> | number
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
  permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>
}

export type RolePermissionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  roleName?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  role?: Prisma.RoleOrderByWithRelationInput
  permission?: Prisma.PermissionOrderByWithRelationInput
}

export type RolePermissionsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  permissionId_appName_resourceName_operationName?: Prisma.RolePermissionsPermissionIdAppNameResourceNameOperationNameCompoundUniqueInput
  AND?: Prisma.RolePermissionsWhereInput | Prisma.RolePermissionsWhereInput[]
  OR?: Prisma.RolePermissionsWhereInput[]
  NOT?: Prisma.RolePermissionsWhereInput | Prisma.RolePermissionsWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
  appName?: Prisma.StringFilter<"RolePermissions"> | string
  appId?: Prisma.IntFilter<"RolePermissions"> | number
  roleName?: Prisma.StringFilter<"RolePermissions"> | string
  roleId?: Prisma.IntFilter<"RolePermissions"> | number
  resourceName?: Prisma.StringFilter<"RolePermissions"> | string
  resourceId?: Prisma.IntFilter<"RolePermissions"> | number
  operationName?: Prisma.StringFilter<"RolePermissions"> | string
  permissionId?: Prisma.IntFilter<"RolePermissions"> | number
  role?: Prisma.XOR<Prisma.RoleScalarRelationFilter, Prisma.RoleWhereInput>
  permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>
}, "id" | "permissionId_appName_resourceName_operationName">

export type RolePermissionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  roleName?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  _count?: Prisma.RolePermissionsCountOrderByAggregateInput
  _avg?: Prisma.RolePermissionsAvgOrderByAggregateInput
  _max?: Prisma.RolePermissionsMaxOrderByAggregateInput
  _min?: Prisma.RolePermissionsMinOrderByAggregateInput
  _sum?: Prisma.RolePermissionsSumOrderByAggregateInput
}

export type RolePermissionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.RolePermissionsScalarWhereWithAggregatesInput | Prisma.RolePermissionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.RolePermissionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RolePermissionsScalarWhereWithAggregatesInput | Prisma.RolePermissionsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"RolePermissions"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RolePermissions"> | Date | string
  appName?: Prisma.StringWithAggregatesFilter<"RolePermissions"> | string
  appId?: Prisma.IntWithAggregatesFilter<"RolePermissions"> | number
  roleName?: Prisma.StringWithAggregatesFilter<"RolePermissions"> | string
  roleId?: Prisma.IntWithAggregatesFilter<"RolePermissions"> | number
  resourceName?: Prisma.StringWithAggregatesFilter<"RolePermissions"> | string
  resourceId?: Prisma.IntWithAggregatesFilter<"RolePermissions"> | number
  operationName?: Prisma.StringWithAggregatesFilter<"RolePermissions"> | string
  permissionId?: Prisma.IntWithAggregatesFilter<"RolePermissions"> | number
}

export type RolePermissionsCreateInput = {
  createdAt?: Date | string
  role: Prisma.RoleCreateNestedOneWithoutRolePermissionsInput
  permission: Prisma.PermissionCreateNestedOneWithoutRolePermissionsInput
}

export type RolePermissionsUncheckedCreateInput = {
  id?: number
  createdAt?: Date | string
  appName: string
  appId: number
  roleName: string
  roleId: number
  resourceName: string
  resourceId: number
  operationName: string
  permissionId: number
}

export type RolePermissionsUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.RoleUpdateOneRequiredWithoutRolePermissionsNestedInput
  permission?: Prisma.PermissionUpdateOneRequiredWithoutRolePermissionsNestedInput
}

export type RolePermissionsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appName?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  roleName?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.IntFieldUpdateOperationsInput | number
  resourceName?: Prisma.StringFieldUpdateOperationsInput | string
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RolePermissionsCreateManyInput = {
  id?: number
  createdAt?: Date | string
  appName: string
  appId: number
  roleName: string
  roleId: number
  resourceName: string
  resourceId: number
  operationName: string
  permissionId: number
}

export type RolePermissionsUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RolePermissionsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appName?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  roleName?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.IntFieldUpdateOperationsInput | number
  resourceName?: Prisma.StringFieldUpdateOperationsInput | string
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RolePermissionsListRelationFilter = {
  every?: Prisma.RolePermissionsWhereInput
  some?: Prisma.RolePermissionsWhereInput
  none?: Prisma.RolePermissionsWhereInput
}

export type RolePermissionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RolePermissionsPermissionIdAppNameResourceNameOperationNameCompoundUniqueInput = {
  permissionId: number
  appName: string
  resourceName: string
  operationName: string
}

export type RolePermissionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  roleName?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type RolePermissionsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type RolePermissionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  roleName?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type RolePermissionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  roleName?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type RolePermissionsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appId?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type RolePermissionsCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRoleInput, Prisma.RolePermissionsUncheckedCreateWithoutRoleInput> | Prisma.RolePermissionsCreateWithoutRoleInput[] | Prisma.RolePermissionsUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutRoleInput | Prisma.RolePermissionsCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.RolePermissionsCreateManyRoleInputEnvelope
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
}

export type RolePermissionsUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRoleInput, Prisma.RolePermissionsUncheckedCreateWithoutRoleInput> | Prisma.RolePermissionsCreateWithoutRoleInput[] | Prisma.RolePermissionsUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutRoleInput | Prisma.RolePermissionsCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.RolePermissionsCreateManyRoleInputEnvelope
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
}

export type RolePermissionsUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRoleInput, Prisma.RolePermissionsUncheckedCreateWithoutRoleInput> | Prisma.RolePermissionsCreateWithoutRoleInput[] | Prisma.RolePermissionsUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutRoleInput | Prisma.RolePermissionsCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.RolePermissionsUpsertWithWhereUniqueWithoutRoleInput | Prisma.RolePermissionsUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.RolePermissionsCreateManyRoleInputEnvelope
  set?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  disconnect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  delete?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  update?: Prisma.RolePermissionsUpdateWithWhereUniqueWithoutRoleInput | Prisma.RolePermissionsUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.RolePermissionsUpdateManyWithWhereWithoutRoleInput | Prisma.RolePermissionsUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
}

export type RolePermissionsUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRoleInput, Prisma.RolePermissionsUncheckedCreateWithoutRoleInput> | Prisma.RolePermissionsCreateWithoutRoleInput[] | Prisma.RolePermissionsUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutRoleInput | Prisma.RolePermissionsCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.RolePermissionsUpsertWithWhereUniqueWithoutRoleInput | Prisma.RolePermissionsUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.RolePermissionsCreateManyRoleInputEnvelope
  set?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  disconnect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  delete?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  update?: Prisma.RolePermissionsUpdateWithWhereUniqueWithoutRoleInput | Prisma.RolePermissionsUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.RolePermissionsUpdateManyWithWhereWithoutRoleInput | Prisma.RolePermissionsUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
}

export type RolePermissionsCreateNestedManyWithoutPermissionInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutPermissionInput, Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput> | Prisma.RolePermissionsCreateWithoutPermissionInput[] | Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutPermissionInput | Prisma.RolePermissionsCreateOrConnectWithoutPermissionInput[]
  createMany?: Prisma.RolePermissionsCreateManyPermissionInputEnvelope
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
}

export type RolePermissionsUncheckedCreateNestedManyWithoutPermissionInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutPermissionInput, Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput> | Prisma.RolePermissionsCreateWithoutPermissionInput[] | Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutPermissionInput | Prisma.RolePermissionsCreateOrConnectWithoutPermissionInput[]
  createMany?: Prisma.RolePermissionsCreateManyPermissionInputEnvelope
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
}

export type RolePermissionsUpdateManyWithoutPermissionNestedInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutPermissionInput, Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput> | Prisma.RolePermissionsCreateWithoutPermissionInput[] | Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutPermissionInput | Prisma.RolePermissionsCreateOrConnectWithoutPermissionInput[]
  upsert?: Prisma.RolePermissionsUpsertWithWhereUniqueWithoutPermissionInput | Prisma.RolePermissionsUpsertWithWhereUniqueWithoutPermissionInput[]
  createMany?: Prisma.RolePermissionsCreateManyPermissionInputEnvelope
  set?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  disconnect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  delete?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  update?: Prisma.RolePermissionsUpdateWithWhereUniqueWithoutPermissionInput | Prisma.RolePermissionsUpdateWithWhereUniqueWithoutPermissionInput[]
  updateMany?: Prisma.RolePermissionsUpdateManyWithWhereWithoutPermissionInput | Prisma.RolePermissionsUpdateManyWithWhereWithoutPermissionInput[]
  deleteMany?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
}

export type RolePermissionsUncheckedUpdateManyWithoutPermissionNestedInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutPermissionInput, Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput> | Prisma.RolePermissionsCreateWithoutPermissionInput[] | Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutPermissionInput | Prisma.RolePermissionsCreateOrConnectWithoutPermissionInput[]
  upsert?: Prisma.RolePermissionsUpsertWithWhereUniqueWithoutPermissionInput | Prisma.RolePermissionsUpsertWithWhereUniqueWithoutPermissionInput[]
  createMany?: Prisma.RolePermissionsCreateManyPermissionInputEnvelope
  set?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  disconnect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  delete?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  update?: Prisma.RolePermissionsUpdateWithWhereUniqueWithoutPermissionInput | Prisma.RolePermissionsUpdateWithWhereUniqueWithoutPermissionInput[]
  updateMany?: Prisma.RolePermissionsUpdateManyWithWhereWithoutPermissionInput | Prisma.RolePermissionsUpdateManyWithWhereWithoutPermissionInput[]
  deleteMany?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
}

export type RolePermissionsCreateWithoutRoleInput = {
  createdAt?: Date | string
  permission: Prisma.PermissionCreateNestedOneWithoutRolePermissionsInput
}

export type RolePermissionsUncheckedCreateWithoutRoleInput = {
  id?: number
  createdAt?: Date | string
  appName: string
  appId: number
  resourceName: string
  resourceId: number
  operationName: string
  permissionId: number
}

export type RolePermissionsCreateOrConnectWithoutRoleInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  create: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRoleInput, Prisma.RolePermissionsUncheckedCreateWithoutRoleInput>
}

export type RolePermissionsCreateManyRoleInputEnvelope = {
  data: Prisma.RolePermissionsCreateManyRoleInput | Prisma.RolePermissionsCreateManyRoleInput[]
  skipDuplicates?: boolean
}

export type RolePermissionsUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  update: Prisma.XOR<Prisma.RolePermissionsUpdateWithoutRoleInput, Prisma.RolePermissionsUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRoleInput, Prisma.RolePermissionsUncheckedCreateWithoutRoleInput>
}

export type RolePermissionsUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  data: Prisma.XOR<Prisma.RolePermissionsUpdateWithoutRoleInput, Prisma.RolePermissionsUncheckedUpdateWithoutRoleInput>
}

export type RolePermissionsUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.RolePermissionsScalarWhereInput
  data: Prisma.XOR<Prisma.RolePermissionsUpdateManyMutationInput, Prisma.RolePermissionsUncheckedUpdateManyWithoutRoleInput>
}

export type RolePermissionsScalarWhereInput = {
  AND?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
  OR?: Prisma.RolePermissionsScalarWhereInput[]
  NOT?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
  id?: Prisma.IntFilter<"RolePermissions"> | number
  createdAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
  appName?: Prisma.StringFilter<"RolePermissions"> | string
  appId?: Prisma.IntFilter<"RolePermissions"> | number
  roleName?: Prisma.StringFilter<"RolePermissions"> | string
  roleId?: Prisma.IntFilter<"RolePermissions"> | number
  resourceName?: Prisma.StringFilter<"RolePermissions"> | string
  resourceId?: Prisma.IntFilter<"RolePermissions"> | number
  operationName?: Prisma.StringFilter<"RolePermissions"> | string
  permissionId?: Prisma.IntFilter<"RolePermissions"> | number
}

export type RolePermissionsCreateWithoutPermissionInput = {
  createdAt?: Date | string
  role: Prisma.RoleCreateNestedOneWithoutRolePermissionsInput
}

export type RolePermissionsUncheckedCreateWithoutPermissionInput = {
  id?: number
  createdAt?: Date | string
  roleName: string
  roleId: number
}

export type RolePermissionsCreateOrConnectWithoutPermissionInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  create: Prisma.XOR<Prisma.RolePermissionsCreateWithoutPermissionInput, Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput>
}

export type RolePermissionsCreateManyPermissionInputEnvelope = {
  data: Prisma.RolePermissionsCreateManyPermissionInput | Prisma.RolePermissionsCreateManyPermissionInput[]
  skipDuplicates?: boolean
}

export type RolePermissionsUpsertWithWhereUniqueWithoutPermissionInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  update: Prisma.XOR<Prisma.RolePermissionsUpdateWithoutPermissionInput, Prisma.RolePermissionsUncheckedUpdateWithoutPermissionInput>
  create: Prisma.XOR<Prisma.RolePermissionsCreateWithoutPermissionInput, Prisma.RolePermissionsUncheckedCreateWithoutPermissionInput>
}

export type RolePermissionsUpdateWithWhereUniqueWithoutPermissionInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  data: Prisma.XOR<Prisma.RolePermissionsUpdateWithoutPermissionInput, Prisma.RolePermissionsUncheckedUpdateWithoutPermissionInput>
}

export type RolePermissionsUpdateManyWithWhereWithoutPermissionInput = {
  where: Prisma.RolePermissionsScalarWhereInput
  data: Prisma.XOR<Prisma.RolePermissionsUpdateManyMutationInput, Prisma.RolePermissionsUncheckedUpdateManyWithoutPermissionInput>
}

export type RolePermissionsCreateManyRoleInput = {
  id?: number
  createdAt?: Date | string
  appName: string
  appId: number
  resourceName: string
  resourceId: number
  operationName: string
  permissionId: number
}

export type RolePermissionsUpdateWithoutRoleInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permission?: Prisma.PermissionUpdateOneRequiredWithoutRolePermissionsNestedInput
}

export type RolePermissionsUncheckedUpdateWithoutRoleInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appName?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  resourceName?: Prisma.StringFieldUpdateOperationsInput | string
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RolePermissionsUncheckedUpdateManyWithoutRoleInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  appName?: Prisma.StringFieldUpdateOperationsInput | string
  appId?: Prisma.IntFieldUpdateOperationsInput | number
  resourceName?: Prisma.StringFieldUpdateOperationsInput | string
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RolePermissionsCreateManyPermissionInput = {
  id?: number
  createdAt?: Date | string
  roleName: string
  roleId: number
}

export type RolePermissionsUpdateWithoutPermissionInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  role?: Prisma.RoleUpdateOneRequiredWithoutRolePermissionsNestedInput
}

export type RolePermissionsUncheckedUpdateWithoutPermissionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  roleName?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RolePermissionsUncheckedUpdateManyWithoutPermissionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  roleName?: Prisma.StringFieldUpdateOperationsInput | string
  roleId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type RolePermissionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  appName?: boolean
  appId?: boolean
  roleName?: boolean
  roleId?: boolean
  resourceName?: boolean
  resourceId?: boolean
  operationName?: boolean
  permissionId?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rolePermissions"]>

export type RolePermissionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  appName?: boolean
  appId?: boolean
  roleName?: boolean
  roleId?: boolean
  resourceName?: boolean
  resourceId?: boolean
  operationName?: boolean
  permissionId?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rolePermissions"]>

export type RolePermissionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  appName?: boolean
  appId?: boolean
  roleName?: boolean
  roleId?: boolean
  resourceName?: boolean
  resourceId?: boolean
  operationName?: boolean
  permissionId?: boolean
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rolePermissions"]>

export type RolePermissionsSelectScalar = {
  id?: boolean
  createdAt?: boolean
  appName?: boolean
  appId?: boolean
  roleName?: boolean
  roleId?: boolean
  resourceName?: boolean
  resourceId?: boolean
  operationName?: boolean
  permissionId?: boolean
}

export type RolePermissionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "appName" | "appId" | "roleName" | "roleId" | "resourceName" | "resourceId" | "operationName" | "permissionId", ExtArgs["result"]["rolePermissions"]>
export type RolePermissionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}
export type RolePermissionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}
export type RolePermissionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.RoleDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}

export type $RolePermissionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RolePermissions"
  objects: {
    role: Prisma.$RolePayload<ExtArgs>
    permission: Prisma.$PermissionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    createdAt: Date
    appName: string
    appId: number
    roleName: string
    roleId: number
    resourceName: string
    resourceId: number
    operationName: string
    permissionId: number
  }, ExtArgs["result"]["rolePermissions"]>
  composites: {}
}

export type RolePermissionsGetPayload<S extends boolean | null | undefined | RolePermissionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload, S>

export type RolePermissionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RolePermissionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RolePermissionsCountAggregateInputType | true
  }

export interface RolePermissionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RolePermissions'], meta: { name: 'RolePermissions' } }
  /**
   * Find zero or one RolePermissions that matches the filter.
   * @param {RolePermissionsFindUniqueArgs} args - Arguments to find a RolePermissions
   * @example
   * // Get one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RolePermissionsFindUniqueArgs>(args: Prisma.SelectSubset<T, RolePermissionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RolePermissions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RolePermissionsFindUniqueOrThrowArgs} args - Arguments to find a RolePermissions
   * @example
   * // Get one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RolePermissionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RolePermissionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RolePermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsFindFirstArgs} args - Arguments to find a RolePermissions
   * @example
   * // Get one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RolePermissionsFindFirstArgs>(args?: Prisma.SelectSubset<T, RolePermissionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RolePermissions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsFindFirstOrThrowArgs} args - Arguments to find a RolePermissions
   * @example
   * // Get one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RolePermissionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RolePermissionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RolePermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findMany()
   * 
   * // Get first 10 RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const rolePermissionsWithIdOnly = await prisma.rolePermissions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RolePermissionsFindManyArgs>(args?: Prisma.SelectSubset<T, RolePermissionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RolePermissions.
   * @param {RolePermissionsCreateArgs} args - Arguments to create a RolePermissions.
   * @example
   * // Create one RolePermissions
   * const RolePermissions = await prisma.rolePermissions.create({
   *   data: {
   *     // ... data to create a RolePermissions
   *   }
   * })
   * 
   */
  create<T extends RolePermissionsCreateArgs>(args: Prisma.SelectSubset<T, RolePermissionsCreateArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RolePermissions.
   * @param {RolePermissionsCreateManyArgs} args - Arguments to create many RolePermissions.
   * @example
   * // Create many RolePermissions
   * const rolePermissions = await prisma.rolePermissions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RolePermissionsCreateManyArgs>(args?: Prisma.SelectSubset<T, RolePermissionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RolePermissions and returns the data saved in the database.
   * @param {RolePermissionsCreateManyAndReturnArgs} args - Arguments to create many RolePermissions.
   * @example
   * // Create many RolePermissions
   * const rolePermissions = await prisma.rolePermissions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RolePermissions and only return the `id`
   * const rolePermissionsWithIdOnly = await prisma.rolePermissions.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RolePermissionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RolePermissionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RolePermissions.
   * @param {RolePermissionsDeleteArgs} args - Arguments to delete one RolePermissions.
   * @example
   * // Delete one RolePermissions
   * const RolePermissions = await prisma.rolePermissions.delete({
   *   where: {
   *     // ... filter to delete one RolePermissions
   *   }
   * })
   * 
   */
  delete<T extends RolePermissionsDeleteArgs>(args: Prisma.SelectSubset<T, RolePermissionsDeleteArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RolePermissions.
   * @param {RolePermissionsUpdateArgs} args - Arguments to update one RolePermissions.
   * @example
   * // Update one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RolePermissionsUpdateArgs>(args: Prisma.SelectSubset<T, RolePermissionsUpdateArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RolePermissions.
   * @param {RolePermissionsDeleteManyArgs} args - Arguments to filter RolePermissions to delete.
   * @example
   * // Delete a few RolePermissions
   * const { count } = await prisma.rolePermissions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RolePermissionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, RolePermissionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RolePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RolePermissions
   * const rolePermissions = await prisma.rolePermissions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RolePermissionsUpdateManyArgs>(args: Prisma.SelectSubset<T, RolePermissionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RolePermissions and returns the data updated in the database.
   * @param {RolePermissionsUpdateManyAndReturnArgs} args - Arguments to update many RolePermissions.
   * @example
   * // Update many RolePermissions
   * const rolePermissions = await prisma.rolePermissions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RolePermissions and only return the `id`
   * const rolePermissionsWithIdOnly = await prisma.rolePermissions.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RolePermissionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RolePermissionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RolePermissions.
   * @param {RolePermissionsUpsertArgs} args - Arguments to update or create a RolePermissions.
   * @example
   * // Update or create a RolePermissions
   * const rolePermissions = await prisma.rolePermissions.upsert({
   *   create: {
   *     // ... data to create a RolePermissions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RolePermissions we want to update
   *   }
   * })
   */
  upsert<T extends RolePermissionsUpsertArgs>(args: Prisma.SelectSubset<T, RolePermissionsUpsertArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RolePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsCountArgs} args - Arguments to filter RolePermissions to count.
   * @example
   * // Count the number of RolePermissions
   * const count = await prisma.rolePermissions.count({
   *   where: {
   *     // ... the filter for the RolePermissions we want to count
   *   }
   * })
  **/
  count<T extends RolePermissionsCountArgs>(
    args?: Prisma.Subset<T, RolePermissionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RolePermissionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RolePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RolePermissionsAggregateArgs>(args: Prisma.Subset<T, RolePermissionsAggregateArgs>): Prisma.PrismaPromise<GetRolePermissionsAggregateType<T>>

  /**
   * Group by RolePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RolePermissionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RolePermissionsGroupByArgs['orderBy'] }
      : { orderBy?: RolePermissionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RolePermissionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRolePermissionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RolePermissions model
 */
readonly fields: RolePermissionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RolePermissions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RolePermissionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  role<T extends Prisma.RoleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoleDefaultArgs<ExtArgs>>): Prisma.Prisma__RoleClient<runtime.Types.Result.GetResult<Prisma.$RolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  permission<T extends Prisma.PermissionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PermissionDefaultArgs<ExtArgs>>): Prisma.Prisma__PermissionClient<runtime.Types.Result.GetResult<Prisma.$PermissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RolePermissions model
 */
export interface RolePermissionsFieldRefs {
  readonly id: Prisma.FieldRef<"RolePermissions", 'Int'>
  readonly createdAt: Prisma.FieldRef<"RolePermissions", 'DateTime'>
  readonly appName: Prisma.FieldRef<"RolePermissions", 'String'>
  readonly appId: Prisma.FieldRef<"RolePermissions", 'Int'>
  readonly roleName: Prisma.FieldRef<"RolePermissions", 'String'>
  readonly roleId: Prisma.FieldRef<"RolePermissions", 'Int'>
  readonly resourceName: Prisma.FieldRef<"RolePermissions", 'String'>
  readonly resourceId: Prisma.FieldRef<"RolePermissions", 'Int'>
  readonly operationName: Prisma.FieldRef<"RolePermissions", 'String'>
  readonly permissionId: Prisma.FieldRef<"RolePermissions", 'Int'>
}
    

// Custom InputTypes
/**
 * RolePermissions findUnique
 */
export type RolePermissionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
}

/**
 * RolePermissions findUniqueOrThrow
 */
export type RolePermissionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
}

/**
 * RolePermissions findFirst
 */
export type RolePermissionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RolePermissions to fetch.
   */
  orderBy?: Prisma.RolePermissionsOrderByWithRelationInput | Prisma.RolePermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RolePermissions.
   */
  cursor?: Prisma.RolePermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RolePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RolePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RolePermissions.
   */
  distinct?: Prisma.RolePermissionsScalarFieldEnum | Prisma.RolePermissionsScalarFieldEnum[]
}

/**
 * RolePermissions findFirstOrThrow
 */
export type RolePermissionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RolePermissions to fetch.
   */
  orderBy?: Prisma.RolePermissionsOrderByWithRelationInput | Prisma.RolePermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RolePermissions.
   */
  cursor?: Prisma.RolePermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RolePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RolePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RolePermissions.
   */
  distinct?: Prisma.RolePermissionsScalarFieldEnum | Prisma.RolePermissionsScalarFieldEnum[]
}

/**
 * RolePermissions findMany
 */
export type RolePermissionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RolePermissions to fetch.
   */
  orderBy?: Prisma.RolePermissionsOrderByWithRelationInput | Prisma.RolePermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RolePermissions.
   */
  cursor?: Prisma.RolePermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RolePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RolePermissions.
   */
  skip?: number
  distinct?: Prisma.RolePermissionsScalarFieldEnum | Prisma.RolePermissionsScalarFieldEnum[]
}

/**
 * RolePermissions create
 */
export type RolePermissionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * The data needed to create a RolePermissions.
   */
  data: Prisma.XOR<Prisma.RolePermissionsCreateInput, Prisma.RolePermissionsUncheckedCreateInput>
}

/**
 * RolePermissions createMany
 */
export type RolePermissionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RolePermissions.
   */
  data: Prisma.RolePermissionsCreateManyInput | Prisma.RolePermissionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RolePermissions createManyAndReturn
 */
export type RolePermissionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * The data used to create many RolePermissions.
   */
  data: Prisma.RolePermissionsCreateManyInput | Prisma.RolePermissionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RolePermissions update
 */
export type RolePermissionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * The data needed to update a RolePermissions.
   */
  data: Prisma.XOR<Prisma.RolePermissionsUpdateInput, Prisma.RolePermissionsUncheckedUpdateInput>
  /**
   * Choose, which RolePermissions to update.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
}

/**
 * RolePermissions updateMany
 */
export type RolePermissionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RolePermissions.
   */
  data: Prisma.XOR<Prisma.RolePermissionsUpdateManyMutationInput, Prisma.RolePermissionsUncheckedUpdateManyInput>
  /**
   * Filter which RolePermissions to update
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * Limit how many RolePermissions to update.
   */
  limit?: number
}

/**
 * RolePermissions updateManyAndReturn
 */
export type RolePermissionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * The data used to update RolePermissions.
   */
  data: Prisma.XOR<Prisma.RolePermissionsUpdateManyMutationInput, Prisma.RolePermissionsUncheckedUpdateManyInput>
  /**
   * Filter which RolePermissions to update
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * Limit how many RolePermissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RolePermissions upsert
 */
export type RolePermissionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * The filter to search for the RolePermissions to update in case it exists.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
  /**
   * In case the RolePermissions found by the `where` argument doesn't exist, create a new RolePermissions with this data.
   */
  create: Prisma.XOR<Prisma.RolePermissionsCreateInput, Prisma.RolePermissionsUncheckedCreateInput>
  /**
   * In case the RolePermissions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RolePermissionsUpdateInput, Prisma.RolePermissionsUncheckedUpdateInput>
}

/**
 * RolePermissions delete
 */
export type RolePermissionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter which RolePermissions to delete.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
}

/**
 * RolePermissions deleteMany
 */
export type RolePermissionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RolePermissions to delete
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * Limit how many RolePermissions to delete.
   */
  limit?: number
}

/**
 * RolePermissions without action
 */
export type RolePermissionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
}
