
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SessionPermission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SessionPermission
 * 
 */
export type SessionPermissionModel = runtime.Types.Result.DefaultSelection<Prisma.$SessionPermissionPayload>

export type AggregateSessionPermission = {
  _count: SessionPermissionCountAggregateOutputType | null
  _avg: SessionPermissionAvgAggregateOutputType | null
  _sum: SessionPermissionSumAggregateOutputType | null
  _min: SessionPermissionMinAggregateOutputType | null
  _max: SessionPermissionMaxAggregateOutputType | null
}

export type SessionPermissionAvgAggregateOutputType = {
  id: number | null
  sessionId: number | null
  permissionId: number | null
}

export type SessionPermissionSumAggregateOutputType = {
  id: number | null
  sessionId: number | null
  permissionId: number | null
}

export type SessionPermissionMinAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  sessionId: number | null
  permissionId: number | null
  appName: string | null
  operationName: string | null
  resourceName: string | null
}

export type SessionPermissionMaxAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  sessionId: number | null
  permissionId: number | null
  appName: string | null
  operationName: string | null
  resourceName: string | null
}

export type SessionPermissionCountAggregateOutputType = {
  id: number
  createdAt: number
  sessionId: number
  permissionId: number
  appName: number
  operationName: number
  resourceName: number
  _all: number
}


export type SessionPermissionAvgAggregateInputType = {
  id?: true
  sessionId?: true
  permissionId?: true
}

export type SessionPermissionSumAggregateInputType = {
  id?: true
  sessionId?: true
  permissionId?: true
}

export type SessionPermissionMinAggregateInputType = {
  id?: true
  createdAt?: true
  sessionId?: true
  permissionId?: true
  appName?: true
  operationName?: true
  resourceName?: true
}

export type SessionPermissionMaxAggregateInputType = {
  id?: true
  createdAt?: true
  sessionId?: true
  permissionId?: true
  appName?: true
  operationName?: true
  resourceName?: true
}

export type SessionPermissionCountAggregateInputType = {
  id?: true
  createdAt?: true
  sessionId?: true
  permissionId?: true
  appName?: true
  operationName?: true
  resourceName?: true
  _all?: true
}

export type SessionPermissionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionPermission to aggregate.
   */
  where?: Prisma.SessionPermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPermissions to fetch.
   */
  orderBy?: Prisma.SessionPermissionOrderByWithRelationInput | Prisma.SessionPermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SessionPermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SessionPermissions
  **/
  _count?: true | SessionPermissionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SessionPermissionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SessionPermissionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SessionPermissionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SessionPermissionMaxAggregateInputType
}

export type GetSessionPermissionAggregateType<T extends SessionPermissionAggregateArgs> = {
      [P in keyof T & keyof AggregateSessionPermission]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSessionPermission[P]>
    : Prisma.GetScalarType<T[P], AggregateSessionPermission[P]>
}




export type SessionPermissionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionPermissionWhereInput
  orderBy?: Prisma.SessionPermissionOrderByWithAggregationInput | Prisma.SessionPermissionOrderByWithAggregationInput[]
  by: Prisma.SessionPermissionScalarFieldEnum[] | Prisma.SessionPermissionScalarFieldEnum
  having?: Prisma.SessionPermissionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SessionPermissionCountAggregateInputType | true
  _avg?: SessionPermissionAvgAggregateInputType
  _sum?: SessionPermissionSumAggregateInputType
  _min?: SessionPermissionMinAggregateInputType
  _max?: SessionPermissionMaxAggregateInputType
}

export type SessionPermissionGroupByOutputType = {
  id: number
  createdAt: Date
  sessionId: number
  permissionId: number
  appName: string
  operationName: string
  resourceName: string
  _count: SessionPermissionCountAggregateOutputType | null
  _avg: SessionPermissionAvgAggregateOutputType | null
  _sum: SessionPermissionSumAggregateOutputType | null
  _min: SessionPermissionMinAggregateOutputType | null
  _max: SessionPermissionMaxAggregateOutputType | null
}

type GetSessionPermissionGroupByPayload<T extends SessionPermissionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SessionPermissionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SessionPermissionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SessionPermissionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SessionPermissionGroupByOutputType[P]>
      }
    >
  >



export type SessionPermissionWhereInput = {
  AND?: Prisma.SessionPermissionWhereInput | Prisma.SessionPermissionWhereInput[]
  OR?: Prisma.SessionPermissionWhereInput[]
  NOT?: Prisma.SessionPermissionWhereInput | Prisma.SessionPermissionWhereInput[]
  id?: Prisma.IntFilter<"SessionPermission"> | number
  createdAt?: Prisma.DateTimeFilter<"SessionPermission"> | Date | string
  sessionId?: Prisma.IntFilter<"SessionPermission"> | number
  permissionId?: Prisma.IntFilter<"SessionPermission"> | number
  appName?: Prisma.StringFilter<"SessionPermission"> | string
  operationName?: Prisma.StringFilter<"SessionPermission"> | string
  resourceName?: Prisma.StringFilter<"SessionPermission"> | string
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>
}

export type SessionPermissionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  session?: Prisma.SessionOrderByWithRelationInput
  permission?: Prisma.PermissionOrderByWithRelationInput
}

export type SessionPermissionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  sessionId_permissionId_appName_operationName_resourceName?: Prisma.SessionPermissionSessionIdPermissionIdAppNameOperationNameResourceNameCompoundUniqueInput
  AND?: Prisma.SessionPermissionWhereInput | Prisma.SessionPermissionWhereInput[]
  OR?: Prisma.SessionPermissionWhereInput[]
  NOT?: Prisma.SessionPermissionWhereInput | Prisma.SessionPermissionWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"SessionPermission"> | Date | string
  sessionId?: Prisma.IntFilter<"SessionPermission"> | number
  permissionId?: Prisma.IntFilter<"SessionPermission"> | number
  appName?: Prisma.StringFilter<"SessionPermission"> | string
  operationName?: Prisma.StringFilter<"SessionPermission"> | string
  resourceName?: Prisma.StringFilter<"SessionPermission"> | string
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  permission?: Prisma.XOR<Prisma.PermissionScalarRelationFilter, Prisma.PermissionWhereInput>
}, "id" | "sessionId_permissionId_appName_operationName_resourceName">

export type SessionPermissionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
  _count?: Prisma.SessionPermissionCountOrderByAggregateInput
  _avg?: Prisma.SessionPermissionAvgOrderByAggregateInput
  _max?: Prisma.SessionPermissionMaxOrderByAggregateInput
  _min?: Prisma.SessionPermissionMinOrderByAggregateInput
  _sum?: Prisma.SessionPermissionSumOrderByAggregateInput
}

export type SessionPermissionScalarWhereWithAggregatesInput = {
  AND?: Prisma.SessionPermissionScalarWhereWithAggregatesInput | Prisma.SessionPermissionScalarWhereWithAggregatesInput[]
  OR?: Prisma.SessionPermissionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SessionPermissionScalarWhereWithAggregatesInput | Prisma.SessionPermissionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SessionPermission"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SessionPermission"> | Date | string
  sessionId?: Prisma.IntWithAggregatesFilter<"SessionPermission"> | number
  permissionId?: Prisma.IntWithAggregatesFilter<"SessionPermission"> | number
  appName?: Prisma.StringWithAggregatesFilter<"SessionPermission"> | string
  operationName?: Prisma.StringWithAggregatesFilter<"SessionPermission"> | string
  resourceName?: Prisma.StringWithAggregatesFilter<"SessionPermission"> | string
}

export type SessionPermissionCreateInput = {
  createdAt?: Date | string
  session: Prisma.SessionCreateNestedOneWithoutSessionPermissionsInput
  permission: Prisma.PermissionCreateNestedOneWithoutAccessTokenPermissionsInput
}

export type SessionPermissionUncheckedCreateInput = {
  id?: number
  createdAt?: Date | string
  sessionId: number
  permissionId: number
  appName: string
  operationName: string
  resourceName: string
}

export type SessionPermissionUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.SessionUpdateOneRequiredWithoutSessionPermissionsNestedInput
  permission?: Prisma.PermissionUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput
}

export type SessionPermissionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
  appName?: Prisma.StringFieldUpdateOperationsInput | string
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  resourceName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SessionPermissionCreateManyInput = {
  id?: number
  createdAt?: Date | string
  sessionId: number
  permissionId: number
  appName: string
  operationName: string
  resourceName: string
}

export type SessionPermissionUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SessionPermissionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
  appName?: Prisma.StringFieldUpdateOperationsInput | string
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  resourceName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SessionPermissionListRelationFilter = {
  every?: Prisma.SessionPermissionWhereInput
  some?: Prisma.SessionPermissionWhereInput
  none?: Prisma.SessionPermissionWhereInput
}

export type SessionPermissionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SessionPermissionSessionIdPermissionIdAppNameOperationNameResourceNameCompoundUniqueInput = {
  sessionId: number
  permissionId: number
  appName: string
  operationName: string
  resourceName: string
}

export type SessionPermissionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
}

export type SessionPermissionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type SessionPermissionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
}

export type SessionPermissionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
  appName?: Prisma.SortOrder
  operationName?: Prisma.SortOrder
  resourceName?: Prisma.SortOrder
}

export type SessionPermissionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  permissionId?: Prisma.SortOrder
}

export type SessionPermissionCreateNestedManyWithoutPermissionInput = {
  create?: Prisma.XOR<Prisma.SessionPermissionCreateWithoutPermissionInput, Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput> | Prisma.SessionPermissionCreateWithoutPermissionInput[] | Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.SessionPermissionCreateOrConnectWithoutPermissionInput | Prisma.SessionPermissionCreateOrConnectWithoutPermissionInput[]
  createMany?: Prisma.SessionPermissionCreateManyPermissionInputEnvelope
  connect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
}

export type SessionPermissionUncheckedCreateNestedManyWithoutPermissionInput = {
  create?: Prisma.XOR<Prisma.SessionPermissionCreateWithoutPermissionInput, Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput> | Prisma.SessionPermissionCreateWithoutPermissionInput[] | Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.SessionPermissionCreateOrConnectWithoutPermissionInput | Prisma.SessionPermissionCreateOrConnectWithoutPermissionInput[]
  createMany?: Prisma.SessionPermissionCreateManyPermissionInputEnvelope
  connect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
}

export type SessionPermissionUpdateManyWithoutPermissionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionPermissionCreateWithoutPermissionInput, Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput> | Prisma.SessionPermissionCreateWithoutPermissionInput[] | Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.SessionPermissionCreateOrConnectWithoutPermissionInput | Prisma.SessionPermissionCreateOrConnectWithoutPermissionInput[]
  upsert?: Prisma.SessionPermissionUpsertWithWhereUniqueWithoutPermissionInput | Prisma.SessionPermissionUpsertWithWhereUniqueWithoutPermissionInput[]
  createMany?: Prisma.SessionPermissionCreateManyPermissionInputEnvelope
  set?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  disconnect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  delete?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  connect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  update?: Prisma.SessionPermissionUpdateWithWhereUniqueWithoutPermissionInput | Prisma.SessionPermissionUpdateWithWhereUniqueWithoutPermissionInput[]
  updateMany?: Prisma.SessionPermissionUpdateManyWithWhereWithoutPermissionInput | Prisma.SessionPermissionUpdateManyWithWhereWithoutPermissionInput[]
  deleteMany?: Prisma.SessionPermissionScalarWhereInput | Prisma.SessionPermissionScalarWhereInput[]
}

export type SessionPermissionUncheckedUpdateManyWithoutPermissionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionPermissionCreateWithoutPermissionInput, Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput> | Prisma.SessionPermissionCreateWithoutPermissionInput[] | Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput[]
  connectOrCreate?: Prisma.SessionPermissionCreateOrConnectWithoutPermissionInput | Prisma.SessionPermissionCreateOrConnectWithoutPermissionInput[]
  upsert?: Prisma.SessionPermissionUpsertWithWhereUniqueWithoutPermissionInput | Prisma.SessionPermissionUpsertWithWhereUniqueWithoutPermissionInput[]
  createMany?: Prisma.SessionPermissionCreateManyPermissionInputEnvelope
  set?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  disconnect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  delete?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  connect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  update?: Prisma.SessionPermissionUpdateWithWhereUniqueWithoutPermissionInput | Prisma.SessionPermissionUpdateWithWhereUniqueWithoutPermissionInput[]
  updateMany?: Prisma.SessionPermissionUpdateManyWithWhereWithoutPermissionInput | Prisma.SessionPermissionUpdateManyWithWhereWithoutPermissionInput[]
  deleteMany?: Prisma.SessionPermissionScalarWhereInput | Prisma.SessionPermissionScalarWhereInput[]
}

export type SessionPermissionCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SessionPermissionCreateWithoutSessionInput, Prisma.SessionPermissionUncheckedCreateWithoutSessionInput> | Prisma.SessionPermissionCreateWithoutSessionInput[] | Prisma.SessionPermissionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionPermissionCreateOrConnectWithoutSessionInput | Prisma.SessionPermissionCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.SessionPermissionCreateManySessionInputEnvelope
  connect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
}

export type SessionPermissionUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SessionPermissionCreateWithoutSessionInput, Prisma.SessionPermissionUncheckedCreateWithoutSessionInput> | Prisma.SessionPermissionCreateWithoutSessionInput[] | Prisma.SessionPermissionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionPermissionCreateOrConnectWithoutSessionInput | Prisma.SessionPermissionCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.SessionPermissionCreateManySessionInputEnvelope
  connect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
}

export type SessionPermissionUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionPermissionCreateWithoutSessionInput, Prisma.SessionPermissionUncheckedCreateWithoutSessionInput> | Prisma.SessionPermissionCreateWithoutSessionInput[] | Prisma.SessionPermissionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionPermissionCreateOrConnectWithoutSessionInput | Prisma.SessionPermissionCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.SessionPermissionUpsertWithWhereUniqueWithoutSessionInput | Prisma.SessionPermissionUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.SessionPermissionCreateManySessionInputEnvelope
  set?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  disconnect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  delete?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  connect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  update?: Prisma.SessionPermissionUpdateWithWhereUniqueWithoutSessionInput | Prisma.SessionPermissionUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.SessionPermissionUpdateManyWithWhereWithoutSessionInput | Prisma.SessionPermissionUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.SessionPermissionScalarWhereInput | Prisma.SessionPermissionScalarWhereInput[]
}

export type SessionPermissionUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionPermissionCreateWithoutSessionInput, Prisma.SessionPermissionUncheckedCreateWithoutSessionInput> | Prisma.SessionPermissionCreateWithoutSessionInput[] | Prisma.SessionPermissionUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionPermissionCreateOrConnectWithoutSessionInput | Prisma.SessionPermissionCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.SessionPermissionUpsertWithWhereUniqueWithoutSessionInput | Prisma.SessionPermissionUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.SessionPermissionCreateManySessionInputEnvelope
  set?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  disconnect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  delete?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  connect?: Prisma.SessionPermissionWhereUniqueInput | Prisma.SessionPermissionWhereUniqueInput[]
  update?: Prisma.SessionPermissionUpdateWithWhereUniqueWithoutSessionInput | Prisma.SessionPermissionUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.SessionPermissionUpdateManyWithWhereWithoutSessionInput | Prisma.SessionPermissionUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.SessionPermissionScalarWhereInput | Prisma.SessionPermissionScalarWhereInput[]
}

export type SessionPermissionCreateWithoutPermissionInput = {
  createdAt?: Date | string
  session: Prisma.SessionCreateNestedOneWithoutSessionPermissionsInput
}

export type SessionPermissionUncheckedCreateWithoutPermissionInput = {
  id?: number
  createdAt?: Date | string
  sessionId: number
}

export type SessionPermissionCreateOrConnectWithoutPermissionInput = {
  where: Prisma.SessionPermissionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionPermissionCreateWithoutPermissionInput, Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput>
}

export type SessionPermissionCreateManyPermissionInputEnvelope = {
  data: Prisma.SessionPermissionCreateManyPermissionInput | Prisma.SessionPermissionCreateManyPermissionInput[]
  skipDuplicates?: boolean
}

export type SessionPermissionUpsertWithWhereUniqueWithoutPermissionInput = {
  where: Prisma.SessionPermissionWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionPermissionUpdateWithoutPermissionInput, Prisma.SessionPermissionUncheckedUpdateWithoutPermissionInput>
  create: Prisma.XOR<Prisma.SessionPermissionCreateWithoutPermissionInput, Prisma.SessionPermissionUncheckedCreateWithoutPermissionInput>
}

export type SessionPermissionUpdateWithWhereUniqueWithoutPermissionInput = {
  where: Prisma.SessionPermissionWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionPermissionUpdateWithoutPermissionInput, Prisma.SessionPermissionUncheckedUpdateWithoutPermissionInput>
}

export type SessionPermissionUpdateManyWithWhereWithoutPermissionInput = {
  where: Prisma.SessionPermissionScalarWhereInput
  data: Prisma.XOR<Prisma.SessionPermissionUpdateManyMutationInput, Prisma.SessionPermissionUncheckedUpdateManyWithoutPermissionInput>
}

export type SessionPermissionScalarWhereInput = {
  AND?: Prisma.SessionPermissionScalarWhereInput | Prisma.SessionPermissionScalarWhereInput[]
  OR?: Prisma.SessionPermissionScalarWhereInput[]
  NOT?: Prisma.SessionPermissionScalarWhereInput | Prisma.SessionPermissionScalarWhereInput[]
  id?: Prisma.IntFilter<"SessionPermission"> | number
  createdAt?: Prisma.DateTimeFilter<"SessionPermission"> | Date | string
  sessionId?: Prisma.IntFilter<"SessionPermission"> | number
  permissionId?: Prisma.IntFilter<"SessionPermission"> | number
  appName?: Prisma.StringFilter<"SessionPermission"> | string
  operationName?: Prisma.StringFilter<"SessionPermission"> | string
  resourceName?: Prisma.StringFilter<"SessionPermission"> | string
}

export type SessionPermissionCreateWithoutSessionInput = {
  createdAt?: Date | string
  permission: Prisma.PermissionCreateNestedOneWithoutAccessTokenPermissionsInput
}

export type SessionPermissionUncheckedCreateWithoutSessionInput = {
  id?: number
  createdAt?: Date | string
  permissionId: number
  appName: string
  operationName: string
  resourceName: string
}

export type SessionPermissionCreateOrConnectWithoutSessionInput = {
  where: Prisma.SessionPermissionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionPermissionCreateWithoutSessionInput, Prisma.SessionPermissionUncheckedCreateWithoutSessionInput>
}

export type SessionPermissionCreateManySessionInputEnvelope = {
  data: Prisma.SessionPermissionCreateManySessionInput | Prisma.SessionPermissionCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type SessionPermissionUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.SessionPermissionWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionPermissionUpdateWithoutSessionInput, Prisma.SessionPermissionUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.SessionPermissionCreateWithoutSessionInput, Prisma.SessionPermissionUncheckedCreateWithoutSessionInput>
}

export type SessionPermissionUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.SessionPermissionWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionPermissionUpdateWithoutSessionInput, Prisma.SessionPermissionUncheckedUpdateWithoutSessionInput>
}

export type SessionPermissionUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.SessionPermissionScalarWhereInput
  data: Prisma.XOR<Prisma.SessionPermissionUpdateManyMutationInput, Prisma.SessionPermissionUncheckedUpdateManyWithoutSessionInput>
}

export type SessionPermissionCreateManyPermissionInput = {
  id?: number
  createdAt?: Date | string
  sessionId: number
}

export type SessionPermissionUpdateWithoutPermissionInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.SessionUpdateOneRequiredWithoutSessionPermissionsNestedInput
}

export type SessionPermissionUncheckedUpdateWithoutPermissionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SessionPermissionUncheckedUpdateManyWithoutPermissionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SessionPermissionCreateManySessionInput = {
  id?: number
  createdAt?: Date | string
  permissionId: number
  appName: string
  operationName: string
  resourceName: string
}

export type SessionPermissionUpdateWithoutSessionInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permission?: Prisma.PermissionUpdateOneRequiredWithoutAccessTokenPermissionsNestedInput
}

export type SessionPermissionUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
  appName?: Prisma.StringFieldUpdateOperationsInput | string
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  resourceName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SessionPermissionUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissionId?: Prisma.IntFieldUpdateOperationsInput | number
  appName?: Prisma.StringFieldUpdateOperationsInput | string
  operationName?: Prisma.StringFieldUpdateOperationsInput | string
  resourceName?: Prisma.StringFieldUpdateOperationsInput | string
}



export type SessionPermissionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  sessionId?: boolean
  permissionId?: boolean
  appName?: boolean
  operationName?: boolean
  resourceName?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionPermission"]>

export type SessionPermissionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  sessionId?: boolean
  permissionId?: boolean
  appName?: boolean
  operationName?: boolean
  resourceName?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionPermission"]>

export type SessionPermissionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  sessionId?: boolean
  permissionId?: boolean
  appName?: boolean
  operationName?: boolean
  resourceName?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionPermission"]>

export type SessionPermissionSelectScalar = {
  id?: boolean
  createdAt?: boolean
  sessionId?: boolean
  permissionId?: boolean
  appName?: boolean
  operationName?: boolean
  resourceName?: boolean
}

export type SessionPermissionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "sessionId" | "permissionId" | "appName" | "operationName" | "resourceName", ExtArgs["result"]["sessionPermission"]>
export type SessionPermissionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}
export type SessionPermissionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}
export type SessionPermissionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  permission?: boolean | Prisma.PermissionDefaultArgs<ExtArgs>
}

export type $SessionPermissionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SessionPermission"
  objects: {
    session: Prisma.$SessionPayload<ExtArgs>
    permission: Prisma.$PermissionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    createdAt: Date
    sessionId: number
    permissionId: number
    appName: string
    operationName: string
    resourceName: string
  }, ExtArgs["result"]["sessionPermission"]>
  composites: {}
}

export type SessionPermissionGetPayload<S extends boolean | null | undefined | SessionPermissionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload, S>

export type SessionPermissionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SessionPermissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SessionPermissionCountAggregateInputType | true
  }

export interface SessionPermissionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SessionPermission'], meta: { name: 'SessionPermission' } }
  /**
   * Find zero or one SessionPermission that matches the filter.
   * @param {SessionPermissionFindUniqueArgs} args - Arguments to find a SessionPermission
   * @example
   * // Get one SessionPermission
   * const sessionPermission = await prisma.sessionPermission.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SessionPermissionFindUniqueArgs>(args: Prisma.SelectSubset<T, SessionPermissionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SessionPermissionClient<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SessionPermission that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SessionPermissionFindUniqueOrThrowArgs} args - Arguments to find a SessionPermission
   * @example
   * // Get one SessionPermission
   * const sessionPermission = await prisma.sessionPermission.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SessionPermissionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SessionPermissionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionPermissionClient<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionPermission that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPermissionFindFirstArgs} args - Arguments to find a SessionPermission
   * @example
   * // Get one SessionPermission
   * const sessionPermission = await prisma.sessionPermission.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SessionPermissionFindFirstArgs>(args?: Prisma.SelectSubset<T, SessionPermissionFindFirstArgs<ExtArgs>>): Prisma.Prisma__SessionPermissionClient<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionPermission that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPermissionFindFirstOrThrowArgs} args - Arguments to find a SessionPermission
   * @example
   * // Get one SessionPermission
   * const sessionPermission = await prisma.sessionPermission.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SessionPermissionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SessionPermissionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionPermissionClient<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SessionPermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPermissionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SessionPermissions
   * const sessionPermissions = await prisma.sessionPermission.findMany()
   * 
   * // Get first 10 SessionPermissions
   * const sessionPermissions = await prisma.sessionPermission.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sessionPermissionWithIdOnly = await prisma.sessionPermission.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SessionPermissionFindManyArgs>(args?: Prisma.SelectSubset<T, SessionPermissionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SessionPermission.
   * @param {SessionPermissionCreateArgs} args - Arguments to create a SessionPermission.
   * @example
   * // Create one SessionPermission
   * const SessionPermission = await prisma.sessionPermission.create({
   *   data: {
   *     // ... data to create a SessionPermission
   *   }
   * })
   * 
   */
  create<T extends SessionPermissionCreateArgs>(args: Prisma.SelectSubset<T, SessionPermissionCreateArgs<ExtArgs>>): Prisma.Prisma__SessionPermissionClient<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SessionPermissions.
   * @param {SessionPermissionCreateManyArgs} args - Arguments to create many SessionPermissions.
   * @example
   * // Create many SessionPermissions
   * const sessionPermission = await prisma.sessionPermission.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SessionPermissionCreateManyArgs>(args?: Prisma.SelectSubset<T, SessionPermissionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SessionPermissions and returns the data saved in the database.
   * @param {SessionPermissionCreateManyAndReturnArgs} args - Arguments to create many SessionPermissions.
   * @example
   * // Create many SessionPermissions
   * const sessionPermission = await prisma.sessionPermission.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SessionPermissions and only return the `id`
   * const sessionPermissionWithIdOnly = await prisma.sessionPermission.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SessionPermissionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SessionPermissionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SessionPermission.
   * @param {SessionPermissionDeleteArgs} args - Arguments to delete one SessionPermission.
   * @example
   * // Delete one SessionPermission
   * const SessionPermission = await prisma.sessionPermission.delete({
   *   where: {
   *     // ... filter to delete one SessionPermission
   *   }
   * })
   * 
   */
  delete<T extends SessionPermissionDeleteArgs>(args: Prisma.SelectSubset<T, SessionPermissionDeleteArgs<ExtArgs>>): Prisma.Prisma__SessionPermissionClient<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SessionPermission.
   * @param {SessionPermissionUpdateArgs} args - Arguments to update one SessionPermission.
   * @example
   * // Update one SessionPermission
   * const sessionPermission = await prisma.sessionPermission.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SessionPermissionUpdateArgs>(args: Prisma.SelectSubset<T, SessionPermissionUpdateArgs<ExtArgs>>): Prisma.Prisma__SessionPermissionClient<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SessionPermissions.
   * @param {SessionPermissionDeleteManyArgs} args - Arguments to filter SessionPermissions to delete.
   * @example
   * // Delete a few SessionPermissions
   * const { count } = await prisma.sessionPermission.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SessionPermissionDeleteManyArgs>(args?: Prisma.SelectSubset<T, SessionPermissionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPermissionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SessionPermissions
   * const sessionPermission = await prisma.sessionPermission.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SessionPermissionUpdateManyArgs>(args: Prisma.SelectSubset<T, SessionPermissionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionPermissions and returns the data updated in the database.
   * @param {SessionPermissionUpdateManyAndReturnArgs} args - Arguments to update many SessionPermissions.
   * @example
   * // Update many SessionPermissions
   * const sessionPermission = await prisma.sessionPermission.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SessionPermissions and only return the `id`
   * const sessionPermissionWithIdOnly = await prisma.sessionPermission.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SessionPermissionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SessionPermissionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SessionPermission.
   * @param {SessionPermissionUpsertArgs} args - Arguments to update or create a SessionPermission.
   * @example
   * // Update or create a SessionPermission
   * const sessionPermission = await prisma.sessionPermission.upsert({
   *   create: {
   *     // ... data to create a SessionPermission
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SessionPermission we want to update
   *   }
   * })
   */
  upsert<T extends SessionPermissionUpsertArgs>(args: Prisma.SelectSubset<T, SessionPermissionUpsertArgs<ExtArgs>>): Prisma.Prisma__SessionPermissionClient<runtime.Types.Result.GetResult<Prisma.$SessionPermissionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SessionPermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPermissionCountArgs} args - Arguments to filter SessionPermissions to count.
   * @example
   * // Count the number of SessionPermissions
   * const count = await prisma.sessionPermission.count({
   *   where: {
   *     // ... the filter for the SessionPermissions we want to count
   *   }
   * })
  **/
  count<T extends SessionPermissionCountArgs>(
    args?: Prisma.Subset<T, SessionPermissionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SessionPermissionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SessionPermission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPermissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SessionPermissionAggregateArgs>(args: Prisma.Subset<T, SessionPermissionAggregateArgs>): Prisma.PrismaPromise<GetSessionPermissionAggregateType<T>>

  /**
   * Group by SessionPermission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPermissionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SessionPermissionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SessionPermissionGroupByArgs['orderBy'] }
      : { orderBy?: SessionPermissionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SessionPermissionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSessionPermissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SessionPermission model
 */
readonly fields: SessionPermissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SessionPermission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SessionPermissionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.SessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SessionDefaultArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  permission<T extends Prisma.PermissionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PermissionDefaultArgs<ExtArgs>>): Prisma.Prisma__PermissionClient<runtime.Types.Result.GetResult<Prisma.$PermissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SessionPermission model
 */
export interface SessionPermissionFieldRefs {
  readonly id: Prisma.FieldRef<"SessionPermission", 'Int'>
  readonly createdAt: Prisma.FieldRef<"SessionPermission", 'DateTime'>
  readonly sessionId: Prisma.FieldRef<"SessionPermission", 'Int'>
  readonly permissionId: Prisma.FieldRef<"SessionPermission", 'Int'>
  readonly appName: Prisma.FieldRef<"SessionPermission", 'String'>
  readonly operationName: Prisma.FieldRef<"SessionPermission", 'String'>
  readonly resourceName: Prisma.FieldRef<"SessionPermission", 'String'>
}
    

// Custom InputTypes
/**
 * SessionPermission findUnique
 */
export type SessionPermissionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * Filter, which SessionPermission to fetch.
   */
  where: Prisma.SessionPermissionWhereUniqueInput
}

/**
 * SessionPermission findUniqueOrThrow
 */
export type SessionPermissionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * Filter, which SessionPermission to fetch.
   */
  where: Prisma.SessionPermissionWhereUniqueInput
}

/**
 * SessionPermission findFirst
 */
export type SessionPermissionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * Filter, which SessionPermission to fetch.
   */
  where?: Prisma.SessionPermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPermissions to fetch.
   */
  orderBy?: Prisma.SessionPermissionOrderByWithRelationInput | Prisma.SessionPermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionPermissions.
   */
  cursor?: Prisma.SessionPermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionPermissions.
   */
  distinct?: Prisma.SessionPermissionScalarFieldEnum | Prisma.SessionPermissionScalarFieldEnum[]
}

/**
 * SessionPermission findFirstOrThrow
 */
export type SessionPermissionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * Filter, which SessionPermission to fetch.
   */
  where?: Prisma.SessionPermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPermissions to fetch.
   */
  orderBy?: Prisma.SessionPermissionOrderByWithRelationInput | Prisma.SessionPermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionPermissions.
   */
  cursor?: Prisma.SessionPermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionPermissions.
   */
  distinct?: Prisma.SessionPermissionScalarFieldEnum | Prisma.SessionPermissionScalarFieldEnum[]
}

/**
 * SessionPermission findMany
 */
export type SessionPermissionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * Filter, which SessionPermissions to fetch.
   */
  where?: Prisma.SessionPermissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPermissions to fetch.
   */
  orderBy?: Prisma.SessionPermissionOrderByWithRelationInput | Prisma.SessionPermissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SessionPermissions.
   */
  cursor?: Prisma.SessionPermissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPermissions.
   */
  skip?: number
  distinct?: Prisma.SessionPermissionScalarFieldEnum | Prisma.SessionPermissionScalarFieldEnum[]
}

/**
 * SessionPermission create
 */
export type SessionPermissionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * The data needed to create a SessionPermission.
   */
  data: Prisma.XOR<Prisma.SessionPermissionCreateInput, Prisma.SessionPermissionUncheckedCreateInput>
}

/**
 * SessionPermission createMany
 */
export type SessionPermissionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SessionPermissions.
   */
  data: Prisma.SessionPermissionCreateManyInput | Prisma.SessionPermissionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SessionPermission createManyAndReturn
 */
export type SessionPermissionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * The data used to create many SessionPermissions.
   */
  data: Prisma.SessionPermissionCreateManyInput | Prisma.SessionPermissionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SessionPermission update
 */
export type SessionPermissionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * The data needed to update a SessionPermission.
   */
  data: Prisma.XOR<Prisma.SessionPermissionUpdateInput, Prisma.SessionPermissionUncheckedUpdateInput>
  /**
   * Choose, which SessionPermission to update.
   */
  where: Prisma.SessionPermissionWhereUniqueInput
}

/**
 * SessionPermission updateMany
 */
export type SessionPermissionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SessionPermissions.
   */
  data: Prisma.XOR<Prisma.SessionPermissionUpdateManyMutationInput, Prisma.SessionPermissionUncheckedUpdateManyInput>
  /**
   * Filter which SessionPermissions to update
   */
  where?: Prisma.SessionPermissionWhereInput
  /**
   * Limit how many SessionPermissions to update.
   */
  limit?: number
}

/**
 * SessionPermission updateManyAndReturn
 */
export type SessionPermissionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * The data used to update SessionPermissions.
   */
  data: Prisma.XOR<Prisma.SessionPermissionUpdateManyMutationInput, Prisma.SessionPermissionUncheckedUpdateManyInput>
  /**
   * Filter which SessionPermissions to update
   */
  where?: Prisma.SessionPermissionWhereInput
  /**
   * Limit how many SessionPermissions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SessionPermission upsert
 */
export type SessionPermissionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * The filter to search for the SessionPermission to update in case it exists.
   */
  where: Prisma.SessionPermissionWhereUniqueInput
  /**
   * In case the SessionPermission found by the `where` argument doesn't exist, create a new SessionPermission with this data.
   */
  create: Prisma.XOR<Prisma.SessionPermissionCreateInput, Prisma.SessionPermissionUncheckedCreateInput>
  /**
   * In case the SessionPermission was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SessionPermissionUpdateInput, Prisma.SessionPermissionUncheckedUpdateInput>
}

/**
 * SessionPermission delete
 */
export type SessionPermissionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
  /**
   * Filter which SessionPermission to delete.
   */
  where: Prisma.SessionPermissionWhereUniqueInput
}

/**
 * SessionPermission deleteMany
 */
export type SessionPermissionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionPermissions to delete
   */
  where?: Prisma.SessionPermissionWhereInput
  /**
   * Limit how many SessionPermissions to delete.
   */
  limit?: number
}

/**
 * SessionPermission without action
 */
export type SessionPermissionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPermission
   */
  select?: Prisma.SessionPermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPermission
   */
  omit?: Prisma.SessionPermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionPermissionInclude<ExtArgs> | null
}
