export const Category = {
  name: 'Category',
  dbName: null,
  schema: null,
  fields: [
    {
      name: 'id',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: true,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'Int',
      nativeType: null,
      default: { name: 'autoincrement', args: [] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'createdAt',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'DateTime',
      nativeType: null,
      default: { name: 'now', args: [] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'updatedAt',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'DateTime',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: true,
    },
    {
      name: 'deletedAt',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'DateTime',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'name',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: true,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: ['VarChar', ['255']],
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'parent',
      kind: 'object',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Category',
      nativeType: null,
      relationName: 'children',
      relationFromFields: ['parentId'],
      relationToFields: ['id'],
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'parentId',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: true,
      hasDefaultValue: false,
      type: 'Int',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'children',
      kind: 'object',
      isList: true,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Category',
      nativeType: null,
      relationName: 'children',
      relationFromFields: [],
      relationToFields: [],
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'products',
      kind: 'object',
      isList: true,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Product',
      nativeType: null,
      relationName: 'CategoryToProduct',
      relationFromFields: [],
      relationToFields: [],
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@hidden',
    },
  ],
  primaryKey: null,
  uniqueFields: [],
  uniqueIndexes: [],
  isGenerated: false,
};

export const User = {
  name: 'User',
  dbName: null,
  schema: null,
  fields: [
    {
      name: 'id',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: true,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'Int',
      nativeType: null,
      default: { name: 'autoincrement', args: [] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'uuid',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'String',
      nativeType: ['Uuid', []],
      default: { name: 'uuid', args: [7] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'createdAt',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'DateTime',
      nativeType: null,
      default: { name: 'now', args: [] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'updatedAt',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'DateTime',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: true,
    },
    {
      name: 'deletedAt',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'DateTime',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'username',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: true,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@email',
    },
    {
      name: 'password',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@password',
    },
    {
      name: 'updatedProducts',
      kind: 'object',
      isList: true,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Product',
      nativeType: null,
      relationName: 'Updater',
      relationFromFields: [],
      relationToFields: [],
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@hidden ',
    },
    {
      name: 'createdProducts',
      kind: 'object',
      isList: true,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Product',
      nativeType: null,
      relationName: 'Creater',
      relationFromFields: [],
      relationToFields: [],
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@hidden ',
    },
  ],
  primaryKey: null,
  uniqueFields: [],
  uniqueIndexes: [],
  isGenerated: false,
};

export const Tag = {
  name: 'Tag',
  dbName: null,
  schema: null,
  fields: [
    {
      name: 'id',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: true,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'Int',
      nativeType: null,
      default: { name: 'autoincrement', args: [] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'name',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: true,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'product',
      kind: 'object',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Product',
      nativeType: null,
      relationName: 'ProductToTag',
      relationFromFields: ['productId'],
      relationToFields: ['id'],
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'productId',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: true,
      hasDefaultValue: false,
      type: 'Int',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
  ],
  primaryKey: null,
  uniqueFields: [],
  uniqueIndexes: [],
  isGenerated: false,
};

export const Product = {
  name: 'Product',
  dbName: null,
  schema: null,
  fields: [
    {
      name: 'id',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: true,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'Int',
      nativeType: null,
      default: { name: 'autoincrement', args: [] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'uuid',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'String',
      nativeType: ['Uuid', []],
      default: { name: 'uuid', args: [7] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'createdAt',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'DateTime',
      nativeType: null,
      default: { name: 'now', args: [] },
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'updatedAt',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'DateTime',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: true,
    },
    {
      name: 'deletedAt',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'DateTime',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'name',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: true,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: ['VarChar', ['255']],
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'description',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'ownTags',
      kind: 'scalar',
      isList: true,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'upc',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: true,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@upc',
    },
    {
      name: 'sku',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: true,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'String',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@min(6) @max(13)',
    },
    {
      name: 'attributes',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Json',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'quantity',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'Int',
      nativeType: null,
      default: 0,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'price',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'Decimal',
      nativeType: ['Decimal', ['8', '6']],
      default: 0,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'cost',
      kind: 'scalar',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: true,
      type: 'Decimal',
      nativeType: ['Decimal', ['8', '6']],
      default: 0,
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@lessThan(price)',
    },
    {
      name: 'active',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Boolean',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'category',
      kind: 'object',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Category',
      nativeType: null,
      relationName: 'CategoryToProduct',
      relationFromFields: ['categoryId'],
      relationToFields: ['id'],
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'categoryId',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: true,
      hasDefaultValue: false,
      type: 'Int',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'tags',
      kind: 'object',
      isList: true,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Tag',
      nativeType: null,
      relationName: 'ProductToTag',
      relationFromFields: [],
      relationToFields: [],
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'createdBy',
      kind: 'object',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'User',
      nativeType: null,
      relationName: 'Creater',
      relationFromFields: ['createdById'],
      relationToFields: ['id'],
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@hidden',
    },
    {
      name: 'createdById',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: true,
      hasDefaultValue: false,
      type: 'Int',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@hidden',
    },
    {
      name: 'updatedBy',
      kind: 'object',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'User',
      nativeType: null,
      relationName: 'Updater',
      relationFromFields: ['updatedById'],
      relationToFields: ['id'],
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@hidden',
    },
    {
      name: 'updatedById',
      kind: 'scalar',
      isList: false,
      isRequired: false,
      isUnique: false,
      isId: false,
      isReadOnly: true,
      hasDefaultValue: false,
      type: 'Int',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
      documentation: '@hidden',
    },
    {
      name: 'status',
      kind: 'enum',
      isList: false,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Status',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
    {
      name: 'scopes',
      kind: 'enum',
      isList: true,
      isRequired: true,
      isUnique: false,
      isId: false,
      isReadOnly: false,
      hasDefaultValue: false,
      type: 'Scope',
      nativeType: null,
      isGenerated: false,
      isUpdatedAt: false,
    },
  ],
  primaryKey: null,
  uniqueFields: [],
  uniqueIndexes: [],
  isGenerated: false,
};

export const Status = {
  name: 'Status',
  values: [
    { name: 'ACTIVE', dbName: null },
    { name: 'PASSIVE', dbName: null },
  ],
  dbName: null,
};

export const Scope = {
  name: 'Scope',
  values: [
    { name: 'APP', dbName: null },
    { name: 'Low', dbName: null },
    { name: 'High', dbName: null },
  ],
  dbName: null,
};
