
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Operation = {
  READ: 'READ',
  WRITE: 'WRITE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  MANAGE: 'MANAGE',
  TRIGGER: 'TRIGGER',
  NOTIFY: 'NOTIFY',
  APPROVE: 'APPROVE',
  START: 'START',
  STOP: 'STOP',
  RESTART: 'RESTART',
  REJECT: 'REJECT',
  SUBMIT: 'SUBMIT',
  ARCHIVE: 'ARCHIVE',
  RESTORE: 'RESTORE',
  EXPORT: 'EXPORT',
  IMPORT: 'IMPORT',
  GRANT: 'GRANT',
  REVOKE: 'REVOKE',
  LOCK: 'LOCK',
  UNLOCK: 'UNLOCK',
  SYNC: 'SYNC',
  DEPLOY: 'DEPLOY',
  ROLLBACK: 'ROLLBACK'
} as const

export type Operation = (typeof Operation)[keyof typeof Operation]
